/**
 * Dedicated bilingual response banks for Kurdana Thought Mirror.
 * Counts per category (approx): 10+ ack, 15+ reframe, 15+ kinder, 10+ next.
 */

function pack(enList, kuList) {
  const n = Math.min(enList.length, kuList.length);
  return Array.from({ length: n }, (_, i) => ({ en: enList[i], ku: kuList[i] }));
}

function makeBank(ackEn, ackKu, refEn, refKu, kindEn, kindKu, nextEn, nextKu, shortEn, shortKu) {
  return {
    acknowledgment: pack(ackEn, ackKu),
    reframe: pack(refEn, refKu),
    kinder: pack(kindEn, kindKu),
    next: pack(nextEn, nextKu),
    short: pack(shortEn, shortKu),
    gentlerAck: pack(ackEn.slice(0, 8), ackKu.slice(0, 8)),
    realisticReframe: pack(refEn.slice(5), refKu.slice(5)),
  };
}

const self_worth = makeBank(
  [
    "It sounds like something made you doubt yourself today.",
    "Those words are heavy — something in you is hurting.",
    "I hear how harsh you’re being with yourself right now.",
    "This thought seems tied to feeling not enough.",
    "You’re carrying a sharp story about your worth.",
    "It makes sense that this would weigh on you.",
    "That self-criticism sounds loud tonight.",
    "You’re naming real pain about how you see yourself.",
    "This doesn’t sound small to you — and that matters.",
    "I hear someone who’s tired of feeling inadequate.",
  ],
  [
    "وەک ئەوەی ئەمڕۆ شتێک وای لێکردیت گومان لە خۆت بکەیت.",
    "ئەم وشانه قورسن — شتێک لەناوت بریندارییە.",
    "گوێم لەوەیە چەند سەخت لەگەڵ خۆت دەبیت ئێستا.",
    "ئەم بیرە پەیوەندی بە هەستی «بەس نییە» هەیە.",
    "چیرۆکێکی تیژ لەسەر بەهای خۆت هەڵدەگریت.",
    "ئاساییە ئەمە قورسیت لێ بکات.",
    "ئەم شەرمەزارییە ئەمشەو بەرزە.",
    "ئازارێکی ڕاستەقینە لەسەر خۆبینینت ناودەبەیت.",
    "بۆ تۆ بچووک نییە — و ئەمە گرنگە.",
    "گوێم لە کەسێکە ماندووە لە هەستی ناتەواوی.",
  ],
  [
    "Struggling with one thing does not define your intelligence or worth.",
    "A hard moment is not proof that you are worthless.",
    "Feeling useless and being useless are not the same.",
    "Harsh self-labels often grow from pain, not from the full truth.",
    "You can feel low and still deserve basic kindness.",
    "One chapter of struggle is not the whole book of who you are.",
    "Self-worth isn’t measured by a single day’s performance.",
    "Being human includes days when confidence dips.",
    "The mind can exaggerate weakness when you’re already tired.",
    "Doubt can visit without becoming your identity.",
    "You are more than the worst thing you tell yourself.",
    "Difficulty does not erase the value of your effort.",
    "Feeling broken often means something needs care — not that you are beyond repair.",
    "Worth isn’t something you earn by never messing up.",
    "This thought is loud, but it isn’t a fair judge of you.",
  ],
  [
    "سەختی لە یەک شتدا مانای ئەوە نییە زیر و بەهایت دیاری دەکات.",
    "کاتێکی قورس بەڵگە نییە کە بێبەها بیت.",
    "هەستی بێسوودی و بێسوود بوون یەک شت نین.",
    "ناوی سەخت بۆ خۆت زۆرجار لە ئازارەوە دێت، نەک لە هەموو ڕاستییەوە.",
    "دەتوانیت نزم هەست بکەیت و هێشتا شایستەی میهرەبانی بیت.",
    "یەک بەشی سەختییەکان هەموو چیرۆکی تۆ نین.",
    "بەهای خۆت بە ئەدای یەک ڕۆژ پێوانە ناکرێت.",
    "مرۆڤ بوون واتە ڕۆژانی کە متمانە دەشکێت.",
    "مێشک لاوازی گەورە دەکات کاتێک پێشتر ماندوویت.",
    "گومان دەتوانێت بێت بەبێ ئەوەی ببێتە ناسنامەت.",
    "تۆ زیاتری لە خراپترین شت کە بە خۆت دەڵێیت.",
    "سەختی هەوڵەکانت ناسڕێتەوە.",
    "هەستی تێکچوون زۆرجار واتە پێویستیت بە چاودێرییە — نەک چارەسەرنەکراو بیت.",
    "بەها شتێک نییە بە هەرگیز هەڵە نەکردن دەست دەکەوێت.",
    "ئەم بیرە بەرزە، بەڵام دادوەرێکی دادپەروەر نییە بۆ تۆ.",
  ],
  [
    "I may not understand this yet, but I can learn it step by step.",
    "I am allowed to be unfinished and still worthy of care.",
    "This feeling is visiting me — it isn’t the whole truth about me.",
    "I can treat the hurting part of me with more softness today.",
    "One struggle does not make me worthless.",
    "I can measure myself by effort and honesty, not perfection.",
    "I deserve patience while I figure this out.",
    "I am learning, even when it feels slow.",
    "My worth isn’t cancelled by a difficult day.",
    "I can be kind to myself without pretending everything is fine.",
    "I don’t have to earn the right to rest or breathe.",
    "I can hold this thought gently without believing every word.",
    "I am more than this harsh sentence.",
    "I can take one small step without fixing my whole self first.",
    "Being imperfect still leaves room for dignity.",
  ],
  [
    "ڕەنگە هێشتا تێنەگەم، بەڵام دەتوانم هەنگاو بە هەنگاو فێر ببم.",
    "مامۆڵەم هەیە ناتەواو بم و هێشتا شایستەی چاودێری بم.",
    "ئەم هەستە سەردانم دەکات — هەموو ڕاستی من نییە.",
    "دەتوانم ئەمڕۆ بە نەرمیتر مامەڵە لەگەڵ بەشی بریندارم بکەم.",
    "یەک سەختی من ناکاتە بێبەها.",
    "دەتوانم خۆم بە هەوڵ و ڕاستگۆیی بپێوم، نەک بە کامڵی.",
    "شایستەی ئارامگیریم کاتێک هێشتا فێردەبم.",
    "فێردەبم، تەنانەت کاتێک هێواش دەردەکەوێت.",
    "بەهایم بە ڕۆژێکی قورس هەڵناوەشێتەوە.",
    "دەتوانم میهرەبان بم لەگەڵ خۆم بەبێ ئەوەی بڵێم هەموو شت باشە.",
    "پێویست ناکات مافی پشوو یان هەناسە بەدەست بهێنم.",
    "دەتوانم ئەم بیرە بە نەرمی هەڵبگرم بەبێ باوەڕکردن بە هەموو وشەیەک.",
    "من زیاترم لەم ڕستە توندە.",
    "دەتوانم یەک هەنگاوی بچووک هەڵبگرم بەبێ چارەسەرکردنی هەموو خۆم.",
    "ناتەواوی هێشتا شوێن بۆ کەرامەت دەهێڵێتەوە.",
  ],
  [
    "Take one small part of the problem and focus only on that.",
    "Drink water, then decide the next tiny action.",
    "Write one kinder sentence beside the harsh one.",
    "Put a hand on your chest and breathe slowly twice.",
    "Ask: what would I say to a friend in this moment?",
    "Step away for two quiet minutes, then return.",
    "Name one thing you did today that took effort.",
    "Choose one task under five minutes and finish only that.",
    "Message someone safe if connection would help.",
    "Sit still for one minute without fixing anything.",
  ],
  [
    "یەک بەشی بچووکی کێشەکە هەڵبژێرە و تەنها لەسەری بوەستە.",
    "ئاو بخۆرەوە، پاشان یەک کرداری بچووک هەڵبژێرە.",
    "یەک ڕستەی میهرەبانتر لە تەنیشت ڕستە توندەکە بنووسە.",
    "دەستت لەسەر سنگت دابنێ و دوو جار هێواش هەناسە بدە.",
    "بپرسە: بە هاوڕێیەک لەم کاتەدا چیم دەوت؟",
    "دوو خولەک بێدەنگ دوور بکەوەرەوە، پاشان بگەڕێوە.",
    "یەک شت ناوببە کە ئەمڕۆ هەوڵی پێویست بوو.",
    "ئەرکێک کەمتر لە پێنج خولەک هەڵبژێرە و تەنها ئەوە تەواو بکە.",
    "ئەگەر پەیوەندی یارمەتی دەدات، بۆ کەسێکی متمانەپێکراو بنووسە.",
    "یەک خولەک دانیشە بەبێ چارەسەرکردنی هیچ شتێک.",
  ],
  [
    "This moment does not define your worth.",
    "One struggle is not the whole of you.",
    "You can be unfinished and still deserve kindness.",
    "This harsh thought is not a fair verdict.",
    "Worth stays even on hard days.",
  ],
  [
    "ئەم کاتە بەهایت دیاری ناکات.",
    "یەک سەختی هەموو تۆ نییە.",
    "دەتوانیت ناتەواو بیت و هێشتا شایستەی میهرەبانی بیت.",
    "ئەم بیری توندە حوکمێکی دادپەروەر نییە.",
    "بەها دەمێنێتەوە تەنانەت لە ڕۆژە قورسەکاندا.",
  ]
);

const failure = makeBank(
  [
    "It sounds like this setback is sitting heavy on you.",
    "Failing at something can feel like failing as a person — that leap is painful.",
    "I hear how much this outcome mattered to you.",
    "You’re naming a real disappointment.",
    "This doesn’t sound like a small miss to you.",
    "The word “failure” gets loud after a hard result.",
    "You’re carrying the weight of what went wrong.",
    "It makes sense to feel shaken after this.",
    "Something didn’t go as hoped — and that hurts.",
    "I hear frustration mixed with self-blame.",
  ],
  [
    "وەک ئەوەی ئەم پاشەکشێیە قورسی لەسەرت دانابێت.",
    "شکست لە شتێکدا دەتوانێت وەک شکستی کەسێک هەست پێ بکرێت — و ئەم بازدانە ئازاربەخشە.",
    "گوێم لەوەیە ئەم ئەنجامە چەند گرنگ بوو بۆت.",
    "نایەمیدی ڕاستەقینە ناودەبەیت.",
    "بۆ تۆ هەڵەیەکی بچووک نییە.",
    "وشەی «شکست» دوای ئەنجامێکی قورس بەرز دەبێتەوە.",
    "قورسی ئەوەی خراپ ڕۆیشت هەڵدەگریت.",
    "ئاساییە دوای ئەمە هەست بە لەرزی بکەیت.",
    "شتێک وەک هیوات نەڕۆیشت — و ئەمە دەئێشێت.",
    "گوێم لە بێزاری تێکەڵ بە خۆسەرزنشتکردنە.",
  ],
  [
    "One mistake is not proof that you always fail.",
    "A failed attempt is information, not a final identity.",
    "Everyone who learns something hard collects unfinished tries.",
    "This result is about one situation, not your entire ability.",
    "Ruining one thing doesn’t mean you ruin everything.",
    "Progress often includes messy middle stages.",
    "You can fail at a task and still be capable of the next try.",
    "“Always” is usually bigger than the actual evidence.",
    "A hard grade or outcome can sting without rewriting your future.",
    "Effort that didn’t land still counts as effort.",
    "You are allowed to recover from a bad attempt.",
    "One loss doesn’t cancel every skill you’ve built.",
    "What went wrong can be reviewed without self-destruction.",
    "Falling short today doesn’t lock tomorrow.",
    "Failure feelings are real; permanent failure is rarely the full story.",
  ],
  [
    "یەک هەڵە بەڵگە نییە کە هەمیشە دەشکێیت.",
    "هەوڵێکی سەرنەکەوتوو زانیارییە، نەک ناسنامەی کۆتایی.",
    "هەر کەسێک شتی سەخت فێر ببێت، هەوڵی ناتەواوی کۆدەکاتەوە.",
    "ئەم ئەنجامە دەربارەی یەک دۆخە، نەک هەموو توانات.",
    "تێکدانی یەک شت مانای تێکدانی هەموو شت نییە.",
    "پێشکەوتن زۆرجار قۆناغی ناڕێکی لە ناوەڕاستدا هەیە.",
    "دەتوانیت لە ئەرکێکدا بشکێیت و هێشتا بۆ هەوڵی داهاتوو توانا بیت.",
    "«هەمیشە» زۆرجار گەورەترە لە بەڵگەی ڕاستەقینە.",
    "نمرە یان ئەنجامێکی قورس دەئێشێت بەبێ نووسینەوەی داهاتووت.",
    "هەوڵێک کە نەگەیشتە ئامانج هێشتا هەوڵە.",
    "مامۆڵەت هەیە لە هەوڵێکی خراپ چاک ببیتەوە.",
    "یەک دۆڕان هەموو لێهاتووییت ناسڕێتەوە.",
    "دەتوانرێت ئەوەی خراپ ڕۆیشت پێداچوونەوە بکرێت بەبێ خۆوێرانکردن.",
    "کەمبوونەوەی ئەمڕۆ سبەینێ قوفڵ ناکات.",
    "هەستی شکست ڕاستەقینەیە؛ شکستی هەمیشەیی بەدەگمەن هەموو چیرۆکەکەیە.",
  ],
  [
    "I can learn from this without calling myself a failure.",
    "This attempt didn’t work — I can try a smaller next step.",
    "One result does not decide every future result.",
    "I can separate the event from my whole identity.",
    "I am allowed to restart without erasing myself.",
    "I can review what happened with curiosity, not cruelty.",
    "Falling short today still leaves room to try again.",
    "I can ask for help on the next attempt.",
    "I don’t have to be perfect to keep going.",
    "This setback is temporary information.",
    "I can choose one repairable piece first.",
    "My story includes retries, not only wins.",
    "I can feel disappointed and still move gently forward.",
    "I am more than this unfinished try.",
    "Next time can be different, even if today was hard.",
  ],
  [
    "دەتوانم لەمە فێر ببم بەبێ ئەوەی خۆم بە شکستخواز ناوببەم.",
    "ئەم هەوڵە کاری نەکرد — دەتوانم هەنگاوێکی بچووکتر تاقی بکەمەوە.",
    "یەک ئەنجام هەموو ئەنجامی داهاتوو یەکلا ناکاتەوە.",
    "دەتوانم ڕووداوەکە لە هەموو ناسنامەم جیا بکەمەوە.",
    "مامۆڵەم هەیە دوبارە دەست پێ بکەمەوە بەبێ سڕینەوەی خۆم.",
    "دەتوانم بە کنجکاوی پێداچوونەوە بکەم، نەک بە توندی.",
    "کەمبوونەوەی ئەمڕۆ هێشتا شوێن بۆ هەوڵی تر دەهێڵێتەوە.",
    "دەتوانم لە هەوڵی داهاتوودا یارمەتی بخوازم.",
    "پێویست ناکات کامڵ بم بۆ بەردەوامبوون.",
    "ئەم پاشەکشێیە زانیارییەکی کاتییە.",
    "دەتوانم یەکەم بەشی چاککراو هەڵبژێرم.",
    "چیرۆکەکەم دووبارە هەوڵدانیشی تێدایە، نەک تەنها سەرکەوتن.",
    "دەتوانم نائومێد بم و هێشتا بە نەرمی بەرەوپێش بڕۆم.",
    "من زیاترم لەم هەوڵە ناتەواوە.",
    "دواتر دەتوانێت جیاواز بێت، تەنانەت ئەگەر ئەمڕۆ قورس بوو.",
  ],
  [
    "Name one concrete detail you can change next time.",
    "Break the next try into a five-minute start.",
    "Write what you learned in one honest line.",
    "Ask one clarifying question if you’re stuck.",
    "Rest briefly, then pick a smaller target.",
    "Review only the part you control.",
    "Practice one skill from the task for ten minutes.",
    "Tell a trusted person the facts, not the self-attack.",
    "Schedule a rematch with yourself tomorrow morning.",
    "Close the day with water and sleep, not a verdict.",
  ],
  [
    "یەک وردەکاری ڕوون ناوببە کە جارێکی تر دەتوانیت بیگۆڕیت.",
    "هەوڵی داهاتوو بکە بە دەستپێکی پێنج خولەک.",
    "ئەوەی فێربوویت لە یەک هێڵی ڕاستگۆدا بنووسە.",
    "ئەگەر قەتیسی، یەک پرسیاری ڕوونکەرەوە بپرسە.",
    "کەمێک پشوو بدە، پاشان ئامانجێکی بچووکتر هەڵبژێرە.",
    "تەنها ئەو بەشە پێداچوونەوە بکە کە لە ژێر دەستتدایە.",
    "دە خولەک یەک لێهاتوویی لە ئەرکەکە ڕاهێنان بکە.",
    "بۆ کەسێکی متمانەپێکراو ڕاستییەکان بڵێ، نەک هێرشی سەر خۆت.",
    "سبەینێ بەیانی دووبارە هەوڵدان بۆ خۆت دیاری بکە.",
    "ڕۆژەکە بە ئاو و خەو دابخە، نەک بە حوکم.",
  ],
  [
    "One result is not proof you always fail.",
    "This attempt can teach without defining you.",
    "You can try a smaller next step.",
    "A setback is temporary information.",
    "You are allowed to restart.",
  ],
  [
    "یەک ئەنجام بەڵگە نییە کە هەمیشە دەشکێیت.",
    "ئەم هەوڵە دەتوانێت فێری بکات بەبێ دیاریکردنی تۆ.",
    "دەتوانیت هەنگاوێکی بچووکتر تاقی بکەیتەوە.",
    "پاشەکشێ زانیارییەکی کاتییە.",
    "مامۆڵەت هەیە دوبارە دەست پێ بکەیتەوە.",
  ]
);

/** Shared filler banks for remaining categories — full bilingual sets. */
function cat(ack, ref, kind, next, short) {
  return makeBank(ack.en, ack.ku, ref.en, ref.ku, kind.en, kind.ku, next.en, next.ku, short.en, short.ku);
}

const loneliness = cat(
  {
    en: [
      "That thought sounds connected to feeling deeply alone right now.",
      "Loneliness can make the mind turn quiet into permanent rejection.",
      "I hear how empty connection feels tonight.",
      "You’re naming a real ache for closeness.",
      "Feeling unseen can hurt more than people admit.",
      "This sounds like distance sitting on your chest.",
      "You’re carrying the weight of not feeling chosen.",
      "Isolation can make every silence feel personal.",
      "I hear longing under these words.",
      "It’s hard when belonging feels far away.",
    ],
    ku: [
      "ئەم بیرە پەیوەندی بە هەستی تەنیایی قووڵەوە هەیە ئێستا.",
      "تەنیایی دەتوانێت مێشک بێدەنگی بکاتە ڕەتکردنەوەی هەمیشەیی.",
      "گوێم لەوەیە پەیوەندی ئەمشەو چەند بەتاڵ هەست دەکات.",
      "ئازاری نزیکبوونەوەی ڕاستەقینە ناودەبەیت.",
      "نەبینراو هەستکردن دەتوانێت زیاتر بئێشێت لەوەی خەڵک دەڵێن.",
      "وەک دوورییەک لەسەر سنگت دانابێت.",
      "قورسی هەستی هەڵنەبژێردراو هەڵدەگریت.",
      "گۆشەگیری دەتوانێت هەر بێدەنگییەک کەسی بکات.",
      "لە ژێر ئەم وشانه دا خواستێک دەبیستم.",
      "سەختە کاتێک هەستی سەر بە شوێنێک دوور دەردەکەوێت.",
    ],
  },
  {
    en: [
      "Feeling alone tonight does not prove you are unwanted.",
      "Loneliness and being unloved are not the same thing.",
      "A quiet evening can feel endless without meaning forever.",
      "Distance from people right now isn’t the full story of your worth.",
      "Connection can be scarce without you being unworthy of it.",
      "The mind often turns temporary isolation into a permanent rule.",
      "You can feel lonely and still matter.",
      "One ignored moment doesn’t erase every bond you’ve had.",
      "Being alone in a room is not the same as being alone in life.",
      "Need for company is human, not weak.",
      "Silence from others can hurt without defining your lovability.",
      "You deserve kindness even when connection feels thin.",
      "Tonight’s emptiness is a feeling, not a final verdict.",
      "Isolation intensifies thoughts — it doesn’t always confirm them.",
      "Belonging can return in small, imperfect ways.",
    ],
    ku: [
      "هەستی تەنیایی ئەمشەو بەڵگە نییە کە نەخوازراویت.",
      "تەنیایی و خۆشەویست نەبوون یەک شت نین.",
      "ئێوارەیەکی بێدەنگ دەتوانێت بێکۆتایی هەست پێ بکرێت بەبێ مانای هەمیشەیی.",
      "دووری لە خەڵک ئێستا هەموو چیرۆکی بەهایت نییە.",
      "پەیوەندی دەتوانێت کەم بێت بەبێ ئەوەی تۆ ناشایستە بیت.",
      "مێشک زۆرجار گۆشەگیری کاتی دەکاتە یاسای هەمیشەیی.",
      "دەتوانیت تەنها هەست بکەیت و هێشتا گرنگ بیت.",
      "یەک کاتی پشتگوێخراو هەموو پەیوەندییەکانت ناسڕێتەوە.",
      "تەنها بوون لە ژوورێکدا وەک تەنها بوون لە ژیاندا نییە.",
      "پێویستی بە هاوڕێیەتی مرۆڤایەتییە، نەک لاوازی.",
      "بێدەنگی کەسانی تر دەئێشێت بەبێ دیاریکردنی شایستەیی خۆشەویستیت.",
      "شایستەی میهرەبانیت تەنانەت کاتێک پەیوەندی تەنکە.",
      "بەتاڵی ئەمشەو هەستە، نەک حوکمی کۆتایی.",
      "گۆشەگیری بیرەکان بەهێز دەکات — هەمیشە پشتڕاستیان ناکاتەوە.",
      "هەستی سەر بە شوێن دەتوانێت بە شێوەی بچووک و ناتەواو بگەڕێتەوە.",
    ],
  },
  {
    en: [
      "I feel alone tonight, but this feeling does not prove I am unwanted.",
      "I can reach for one small connection when I’m ready.",
      "Loneliness is visiting — it isn’t my permanent address.",
      "I deserve company that feels safe, even if it’s not here yet.",
      "I can be gentle with myself in the quiet.",
      "One person who cares is enough to start with.",
      "I matter even when the room is empty.",
      "I can name the loneliness without becoming it.",
      "Tonight is hard; it doesn’t mean forever.",
      "I am allowed to want closeness.",
      "I can send one honest message if it feels safe.",
      "Being unseen right now doesn’t make me invisible forever.",
      "I can hold warmth for myself while I wait for connection.",
      "My need for people is human.",
      "I can survive this evening one hour at a time.",
    ],
    ku: [
      "ئەمشەو تەنهام، بەڵام ئەم هەستە بەڵگە نییە کە نەخوازراوم.",
      "دەتوانم کاتێک ئامادە بم یەک پەیوەندی بچووک بخوازم.",
      "تەنیایی سەردانم دەکات — ناونیشانی هەمیشەیی من نییە.",
      "شایستەی هاوڕێیەتی سەلامەتم، تەنانەت ئەگەر هێشتا لێرە نەبێت.",
      "دەتوانم لە بێدەنگیدا نەرم بم لەگەڵ خۆم.",
      "یەک کەس کە گرنگی پێ بدات بۆ دەستپێک بەسە.",
      "گرنگم تەنانەت کاتێک ژوورەکە بەتاڵە.",
      "دەتوانم تەنیایی ناوببەم بەبێ بوون بە تەنیایی.",
      "ئەمشەو سەختە؛ مانای هەمیشەیی نییە.",
      "مامۆڵەم هەیە نزیکبوونەوە بخوازم.",
      "دەتوانم یەک پەیامی ڕاستگۆ بنێرم ئەگەر سەلامەت بێت.",
      "نەبینراو بوون ئێستا من بۆ هەمیشە نادیار ناکات.",
      "دەتوانم گەرمی بۆ خۆم هەڵبگرم کاتێک چاوەڕێی پەیوەندیم.",
      "پێویستیم بە خەڵک مرۆڤایەتییە.",
      "دەتوانم ئەم ئێوارەیە کاتژمێر بە کاتژمێر تێپەڕێنم.",
    ],
  },
  {
    en: [
      "Would it help to think of one person you might feel safest messaging?",
      "Step outside for two minutes of air, then return.",
      "Put on a calm sound and sit with it briefly.",
      "Write the loneliness in one sentence, then close the note.",
      "Do one kind act for your body: water or a warm wash.",
      "Look at one photo that reminds you of belonging.",
      "Stretch your shoulders and name three things you can see.",
      "If talking feels hard, send a short “thinking of you.”",
      "Plan one small social step for tomorrow, not tonight.",
      "Hold a soft object and breathe slowly four times.",
    ],
    ku: [
      "یارمەتی دەدات بیر لە یەک کەس بکەیتەوە کە دڵنیاترین بیت پەیامی بۆ بنێریت؟",
      "دوو خولەک بچۆ دەرەوە بۆ هەوا، پاشان بگەڕێوە.",
      "دەنگێکی ئارام لێبدە و کەمێک لەگەڵی دانیشە.",
      "تەنیایی لە یەک ڕستەدا بنووسە، پاشان تێبینییەکە دابخە.",
      "یەک کرداری میهرەبان بۆ جەستەت: ئاو یان شوشتنی گەرم.",
      "سەیری یەک وێنە بکە کە بیرت دەخاتەوە لە سەر بە شوێن.",
      "شانەکانت درێژ بکەرەوە و سێ شت ناوببە کە دەیانبینیت.",
      "ئەگەر قسە سەختە، «بیرم لە تۆ دەکەم»ی کورت بنێرە.",
      "یەک هەنگاوی کۆمەڵایەتی بچووک بۆ سبەینێ پلانی بۆ دابنێ، نەک ئەمشەو.",
      "شتێکی نەرم بگرە و چوار جار هێواش هەناسە بدە.",
    ],
  },
  {
    en: [
      "Feeling alone tonight doesn’t prove you’re unwanted.",
      "Loneliness is a feeling, not a final verdict.",
      "You can reach for one small safe connection.",
      "You matter even in a quiet room.",
      "Tonight is hard — not forever.",
    ],
    ku: [
      "تەنیایی ئەمشەو بەڵگە نییە کە نەخوازراویت.",
      "تەنیایی هەستە، نەک حوکمی کۆتایی.",
      "دەتوانیت یەک پەیوەندی سەلامەتی بچووک بخوازیت.",
      "گرنگیت تەنانەت لە ژوورێکی بێدەنگدا.",
      "ئەمشەو سەختە — نەک هەمیشەیی.",
    ],
  }
);

// Continue with remaining categories in a second write via StrReplace append...
// For file size, export BANKS object at end after defining all.

const appearance = cat(
  {
    en: [
      "It sounds like you’re being very hard on how you look today.",
      "Body thoughts can cut deep when confidence is low.",
      "I hear dislike aimed at your reflection.",
      "Appearance pressure is heavy in this moment.",
      "You’re naming real pain about your body or face.",
      "These words sound sharp against yourself.",
      "Looking in the mirror feels unsafe right now.",
      "You’re carrying a harsh story about beauty.",
      "It makes sense this would sting.",
      "I hear exhaustion mixed with self-critique.",
    ],
    ku: [
      "وەک ئەوەی ئەمڕۆ زۆر سەخت بیت لەسەر شێوەت.",
      "بیری جەستە قووڵ دەبڕێت کاتێک متمانە نزمە.",
      "گوێم لە ڕقێکە بەرەو ئاوێنەکەت.",
      "فشاری جوانی لەم کاتەدا قورسە.",
      "ئازارێکی ڕاستەقینە لەسەر جەستە یان ڕووخسارت ناودەبەیت.",
      "ئەم وشانه تیژن دژی خۆت.",
      "سەیری ئاوێنە ئێستا سەلامەت هەست ناکات.",
      "چیرۆکێکی توند لەسەر جوانی هەڵدەگریت.",
      "ئاساییە ئەمە بئێشێت.",
      "گوێم لە ماندوویی تێکەڵ بە ڕەخنەی خۆتە.",
    ],
  },
  {
    en: [
      "Disliking how you look today does not make you unworthy of care.",
      "Bodies change; a harsh glance is not a permanent truth.",
      "Beauty standards are loud — they are not accurate judges.",
      "You can feel uncomfortable in your body and still deserve gentleness.",
      "One mirror moment is not the full story of your presence.",
      "Self-image often darkens when you’re tired or stressed.",
      "Looking different from an ideal is not a moral failure.",
      "You are more than a single feature you dislike.",
      "Kindness toward your body can start small and honest.",
      "Feeling ugly is a feeling — not a verified fact about your worth.",
      "Appearance pressure intensifies under comparison.",
      "Your body carries you; that alone deserves basic respect.",
      "You don’t owe anyone a perfect look to matter.",
      "Harsh body talk often covers deeper exhaustion or fear.",
      "You can seek comfort without waiting to “love” every detail.",
    ],
    ku: [
      "ڕازی نەبوون لە شێوەت ئەمڕۆ ناکاتە ناشایستەی چاودێری.",
      "جەستە دەگۆڕێت؛ سەیرێکی توند ڕاستی هەمیشەیی نییە.",
      "پێوەرەکانی جوانی بەرزن — دادوەری ورد نین.",
      "دەتوانیت نارەحەت بیت لە جەستەت و هێشتا شایستەی نەرمی بیت.",
      "یەک کاتی ئاوێنە هەموو چیرۆکی بوونت نییە.",
      "وێنەی خۆت زۆرجار تاریک دەبێت کاتێک ماندوو یان فشارداریت.",
      "جیاوازبوون لە نموونەیەک شکستێکی ئەخلاقی نییە.",
      "تۆ زیاتری لە یەک تایبەتمەندی کە حەزت لێی نییە.",
      "میهرەبانی بەرامبەر جەستەت دەتوانێت بچووک و ڕاستگۆ دەست پێ بکات.",
      "هەستی ناشرینی هەستە — نەک ڕاستییەکی پشتڕاستکراو لەسەر بەهایت.",
      "فشاری شێوە لەژێر بەراورددا بەهێزتر دەبێت.",
      "جەستەت هەڵت دەگرێت؛ تەنها ئەوەش شایستەی ڕێزێکی بنەڕەتییە.",
      "قەرزاری کەس نیت شێوەی کامڵ بیت بۆ ئەوەی گرنگ بیت.",
      "قسەی توند لەسەر جەستە زۆرجار ماندوویی یان ترسی قووڵتر دەپۆشێت.",
      "دەتوانیت ئارامی بخوازیت بەبێ چاوەڕێی «خۆشویستنی» هەموو وردەکارییەک.",
    ],
  },
  {
    en: [
      "I deserve kindness even when I dislike how I look today.",
      "My body is allowed to exist without earning beauty first.",
      "This harsh glance is temporary — I can soften it.",
      "I can care for myself without waiting to feel beautiful.",
      "I am more than the feature I criticize.",
      "I can dress or move in a way that feels safer today.",
      "One mirror thought does not decide my worth.",
      "I can speak to my body like someone I protect.",
      "I don’t have to look perfect to take up space.",
      "I can rest my eyes from comparison for a while.",
      "Feeling uncomfortable is allowed; cruelty is optional.",
      "I can choose one gentle action for my body now.",
      "My value isn’t measured in a reflection.",
      "I can be unfinished and still respected.",
      "Today I practice respect, not perfection.",
    ],
    ku: [
      "شایستەی میهرەبانیم تەنانەت کاتێک حەزم لە شێوەم نییە ئەمڕۆ.",
      "جەستەم مامۆڵەی هەیە هەبێت بەبێ ئەوەی پێشتر جوانی بەدەست بهێنێت.",
      "ئەم سەیرە توندە کاتییە — دەتوانم نەرمی بکەم.",
      "دەتوانم چاودێری خۆم بکەم بەبێ چاوەڕێی هەستی جوانی.",
      "من زیاترم لەو تایبەتمەندییەی ڕەخنەی لێ دەگرم.",
      "دەتوانم ئەمڕۆ بە شێوەیەک بپۆشم یان بجووڵێم کە سەلامەتتر هەست پێ بکات.",
      "یەک بیری ئاوێنە بەهایم یەکلا ناکاتەوە.",
      "دەتوانم لەگەڵ جەستەم وەک کەسێک قسە بکەم کە دەیپارێزم.",
      "پێویست ناکات کامڵ دەربکەوم بۆ ئەوەی شوێن بگرم.",
      "دەتوانم چاوم لە بەراورد پشوو بدەم بۆ ماوەیەک.",
      "هەستی نارەحەتی ڕێگەپێدراوە؛ توندی هەڵبژاردەیە.",
      "دەتوانم ئێستا یەک کرداری نەرم بۆ جەستەم هەڵبژێرم.",
      "بەهایم بە ئاوێنە پێوانە ناکرێت.",
      "دەتوانم ناتەواو بم و هێشتا ڕێزم لێ بگیرێت.",
      "ئەمڕۆ ڕێز ڕاهێنان دەکەم، نەک کامڵی.",
    ],
  },
  {
    en: [
      "Soften the lighting, look away, and breathe twice.",
      "Drink water and stretch your shoulders gently.",
      "Wear something that feels kind to your skin.",
      "Limit mirror time for the next hour.",
      "Name one non-appearance strength you used today.",
      "Put your phone down if comparison scrolling started.",
      "Wash your face slowly as a care act, not a fix.",
      "Step into a comfortable posture for thirty seconds.",
      "Say one neutral sentence: “This is my body today.”",
      "Ask what your body needs: rest, water, or movement.",
    ],
    ku: [
      "ڕووناکی نەرم بکە، چاو لێ بگەڕێنەوە، و دوو جار هەناسە بدە.",
      "ئاو بخۆرەوە و شانەکانت بە نەرمی درێژ بکەرەوە.",
      "شتێک بپۆشە کە بۆ پێستت میهرەبان بێت.",
      "بۆ کاتژمێری داهاتوو کاتی ئاوێنە کەم بکەرەوە.",
      "یەک هێزی نا-شێوە ناوببە کە ئەمڕۆ بەکارت هێنا.",
      "مۆبایل دابنێ ئەگەر گەڕانی بەراورد دەستی پێکرد.",
      "ڕووخسارت هێواش بشۆ وەک چاودێری، نەک وەک چارەسەر.",
      "سی چرکە لە هەڵوێستێکی ئارامدا بوەستە.",
      "یەک ڕستەی بێلایەن بڵێ: «ئەمە جەستەمە ئەمڕۆ.»",
      "بپرسە جەستەت چی دەوێت: پشوو، ئاو، یان جووڵە.",
    ],
  },
  {
    en: [
      "You deserve kindness even when you dislike how you look.",
      "A harsh mirror moment is not your whole worth.",
      "Your body deserves basic respect today.",
      "You don’t need perfect looks to matter.",
      "Care can start before confidence arrives.",
    ],
    ku: [
      "شایستەی میهرەبانیت تەنانەت کاتێک حەزت لە شێوەت نییە.",
      "کاتێکی توندی ئاوێنە هەموو بەهایت نییە.",
      "جەستەت ئەمڕۆ شایستەی ڕێزی بنەڕەتییە.",
      "پێویست ناکات شێوەی کامڵت هەبێت بۆ ئەوەی گرنگ بیت.",
      "چاودێری دەتوانێت پێش متمانە دەست پێ بکات.",
    ],
  }
);

const exhaustion = cat(
  {
    en: [
      "You’re naming real fatigue — and that honesty matters.",
      "Exhaustion makes everything feel heavier than it is.",
      "I hear a body asking for rest.",
      "Burnout can quiet hope and amplify self-blame.",
      "You’re running on empty, and that shows in these words.",
      "Tiredness is speaking loudly right now.",
      "It sounds like you’ve been carrying too much.",
      "Low energy can make small tasks feel impossible.",
      "You’re describing depletion, not laziness.",
      "I hear the need to slow down.",
    ],
    ku: [
      "ماندوویی ڕاستەقینە ناودەبەیت — و ئەم ڕاستگۆییە گرنگە.",
      "ماندوویی هەموو شت قورستر دەکات لەوەی هەیە.",
      "گوێم لە جەستەیەکە داوای پشوو دەکات.",
      "سووتان دەتوانێت هیوا بێدەنگ بکات و خۆسەرزنشت بەرز بکاتەوە.",
      "بەتاڵ ڕادەکەیت، و لەم وشانه دا دەردەکەوێت.",
      "ماندوویی ئێستا بە دەنگی بەرز قسە دەکات.",
      "وەک ئەوەی زۆر شتت هەڵگرتبێت.",
      "وزەی نزم دەتوانێت ئەرکی بچووک مەحاڵ بکات.",
      "بەتاڵبوون وەسف دەکەیت، نەک سستی.",
      "گوێم لە پێویستی هێواشبوونەوەیە.",
    ],
  },
  {
    en: [
      "Rest isn’t laziness. Your body is asking for care.",
      "Being exhausted doesn’t mean you’re weak or failing.",
      "Energy drops are human, especially after long strain.",
      "You can’t think clearly on an empty battery — that’s biology, not character.",
      "Slowing down can be the responsible choice today.",
      "Depletion often pretends to be permanent; rest can shift it.",
      "Doing less for a while can protect what still matters.",
      "Tired minds invent harsher stories about capability.",
      "You deserve recovery without earning it through more output.",
      "One full day of fatigue doesn’t erase your resilience.",
      "Burnout is a signal to reduce load, not to attack yourself.",
      "Pace is allowed to change when capacity changes.",
      "You can honor limits without calling them failure.",
      "Gentle rest is work your nervous system understands.",
      "Exhaustion lies about forever; it tells the truth about now.",
    ],
    ku: [
      "پشوو سستی نییە. جەستەت داوای چاودێری دەکات.",
      "ماندوو بوون مانای لاواز یان شکستخواز بوون نییە.",
      "دابەزینی وزە مرۆڤایەتییە، بەتایبەتی دوای فشارێکی درێژ.",
      "ناتوانیت بە پاتری بەتاڵ ڕوون بیر بکەیتەوە — ئەمە بایۆلۆجیایە، نەک کەسایەتی.",
      "هێواشبوونەوە ئەمڕۆ دەتوانێت هەڵبژاردەیەکی بەرپرسیارانە بێت.",
      "بەتاڵبوون زۆرجار وەک هەمیشەیی خۆی پیشان دەدات؛ پشوو دەتوانێت بیگۆڕێت.",
      "کەمتر کردن بۆ ماوەیەک دەتوانێت ئەوە بپارێزێت کە هێشتا گرنگە.",
      "مێشکی ماندوو چیرۆکی توندتر لەسەر توانا دروست دەکات.",
      "شایستەی چاکبوونەوەیت بەبێ بەدەستهێنانی بە کارکردنی زیاتر.",
      "یەک ڕۆژی تەواوی ماندوویی خۆڕاگرییەکانت ناسڕێتەوە.",
      "سووتان ئاماژەیە بۆ کەمکردنەوەی بار، نەک هێرشکردنە سەر خۆت.",
      "خێرایی مامۆڵەی هەیە بگۆڕێت کاتێک توانا دەگۆڕێت.",
      "دەتوانیت سنوورەکان ڕێز لێ بگریت بەبێ ناوی شکست.",
      "پشووی نەرم کارێکە سیستەمی دەمارەکەت تێیدەگات.",
      "ماندوویی لەسەر هەمیشەیی درۆ دەکات؛ لەسەر ئێستا ڕاست دەڵێت.",
    ],
  },
  {
    en: [
      "My body is asking for care. Rest is allowed.",
      "I can do one small thing, then pause.",
      "Low energy is a signal, not a verdict on my worth.",
      "I don’t have to finish everything tonight.",
      "I can choose the gentlest next step.",
      "Recovery counts as progress today.",
      "I can lower the bar without shaming myself.",
      "Slow is still moving.",
      "I am allowed to stop before I empty out completely.",
      "One breath and water are enough for this minute.",
      "I can protect my energy like something valuable.",
      "Tired doesn’t mean incapable forever.",
      "I can rest first, decide later.",
      "My pace can match my capacity.",
      "Care now prevents a harder crash later.",
    ],
    ku: [
      "جەستەم داوای چاودێری دەکات. پشوو ڕێگەپێدراوە.",
      "دەتوانم یەک شتی بچووک بکەم، پاشان بوەستم.",
      "وزەی نزم ئاماژەیە، نەک حوکم لەسەر بەهایم.",
      "پێویست ناکات ئەمشەو هەموو شت تەواو بکەم.",
      "دەتوانم نەرمترین هەنگاوی داهاتوو هەڵبژێرم.",
      "چاکبوونەوە ئەمڕۆ وەک پێشکەوتن دەژمێردرێت.",
      "دەتوانم ئاستەکە دابەزێنم بەبێ شەرمەزاری.",
      "هێواش هێشتا جووڵەیە.",
      "مامۆڵەم هەیە بوەستم پێش بەتاڵبوونی تەواو.",
      "یەک هەناسە و ئاو بۆ ئەم خولەکە بەسە.",
      "دەتوانم وزەم وەک شتێکی بەنرخ بپارێزم.",
      "ماندوو مانای بێتوانایی هەمیشەیی نییە.",
      "دەتوانم یەکەم پشوو بدەم، دواتر بڕیار بدەم.",
      "خێراییم دەتوانێت لەگەڵ توانام بگونجێت.",
      "چاودێری ئێستا لە داڕمانی قورستر دواتر دەپارێزێت.",
    ],
  },
  {
    en: [
      "Lie down or sit still for three quiet minutes.",
      "Drink water and loosen your jaw.",
      "Cancel or shrink one non-urgent task.",
      "Dim the screen brightness and rest your eyes.",
      "Eat something simple if you haven’t.",
      "Set a short timer for sleep prep.",
      "Ask someone to help with one load-bearing task.",
      "Stretch slowly for one song length.",
      "Put your body in a warmer or cooler place that soothes.",
      "Choose rest before another self-critique.",
    ],
    ku: [
      "سێ خولەک بێدەنگ ڕاکەشە یان دانیشە.",
      "ئاو بخۆرەوە و چەناگەت شل بکە.",
      "یەک ئەرکی نا-فریاگوزار هەڵبوەشێنە یان بچووکتری بکە.",
      "ڕووناکی شاشە کەم بکە و چاوت پشوو بدە.",
      "ئەگەر نەتخواردووە، شتێکی سادە بخۆ.",
      "تایمەری کورت بۆ ئامادەکردنی خەو دابنێ.",
      "داوا لە کەسێک بکە یارمەتی یەک ئەرکی قورس بدات.",
      "بە درێژایی یەک گۆرانی هێواش درێژ بکەرەوە.",
      "جەستەت لە شوێنێکی گەرمتر یان ساردتر دابنێ کە هێورت بکاتەوە.",
      "پشوو هەڵبژێرە پێش ڕەخنەیەکی تری خۆت.",
    ],
  },
  {
    en: [
      "Rest is allowed. Your body is asking for care.",
      "Tired is a signal, not a character flaw.",
      "Do one small thing, then pause.",
      "You don’t have to finish everything tonight.",
      "Gentle rest counts as progress.",
    ],
    ku: [
      "پشوو ڕێگەپێدراوە. جەستەت داوای چاودێری دەکات.",
      "ماندوویی ئاماژەیە، نەک کەموکوڕی کەسایەتی.",
      "یەک شتی بچووک بکە، پاشان بوەستە.",
      "پێویست ناکات ئەمشەو هەموو شت تەواو بکەیت.",
      "پشووی نەرم وەک پێشکەوتن دەژمێردرێت.",
    ],
  }
);

const anxiety = cat(
  {
    en: [
      "Your body is sounding an alarm. That doesn’t mean you’re broken.",
      "Fear is loud right now — I hear it.",
      "Anxiety can make the future feel sharper than it is.",
      "You’re naming worry that wants control.",
      "It sounds hard to settle your system.",
      "Panic energy can arrive without a clear reason.",
      "I hear tension asking for safety.",
      "Scared thoughts often rush ahead of facts.",
      "You’re in a high-alert state.",
      "This nervousness is real in your body.",
    ],
    ku: [
      "جەستەت زەنگی ئاگاداری لێدەدات. ئەمە مانای تێکچوونت نییە.",
      "ترس ئێستا بەرزە — گوێم لێیە.",
      "دڵەڕاوکێ دەتوانێت داهاتوو تیژتر لە ڕاستی پیشان بدات.",
      "نیگەرانییەک ناودەبەیت کە دەیهەوێت کۆنترۆڵ بکات.",
      "سەختە سیستەمەکەت ئارام ببێتەوە.",
      "وزەی پەنیک دەتوانێت بێ هۆکاری ڕوون بێت.",
      "گوێم لە گرژییەکە داوای سەلامەتی دەکات.",
      "بیری ترسناک زۆرجار پێش ڕاستییەکان ڕادەکات.",
      "لە دۆخی وریایی بەرزدایت.",
      "ئەم دڵەڕاوکێیە لە جەستەتدا ڕاستەقینەیە.",
    ],
  },
  {
    en: [
      "Feeling scared doesn’t mean danger is certain.",
      "Anxiety often predicts; it doesn’t always report accurately.",
      "You can feel fear and still take one grounding second.",
      "A racing mind is uncomfortable — it isn’t proof you can’t cope.",
      "Alarm signals can be false alarms and still feel real.",
      "You don’t have to solve the whole future to calm the next minute.",
      "Worry expands; facts can shrink it gently.",
      "Being on edge is temporary for many waves of anxiety.",
      "You can slow the body even when thoughts stay busy.",
      "Uncertainty is hard; it isn’t the same as catastrophe.",
      "Panic peaks and eases — riding one breath helps.",
      "You are allowed to seek safety cues in the room.",
      "Fear can visit without owning the whole evening.",
      "Your nervous system can learn “enough for now.”",
      "Calm isn’t required for a tiny next step.",
    ],
    ku: [
      "هەستی ترس مانای ئەوە نییە مەترسی دڵنیایە.",
      "دڵەڕاوکێ زۆرجار پێشبینی دەکات؛ هەمیشە ڕاپۆرتی ورد نادات.",
      "دەتوانیت بترسیت و هێشتا یەک چرکە بگەڕێیتەوە بۆ ئێستا.",
      "مێشکی خێرا نارەحەتە — بەڵگە نییە ناتوانیت بەرگە بگریت.",
      "ئاماژەی زەنگ دەتوانێت هەڵە بێت و هێشتا ڕاستەقینە هەست پێ بکرێت.",
      "پێویست ناکات هەموو داهاتوو چارەسەر بکەیت بۆ ئارامکردنی خولەکی داهاتوو.",
      "نیگەران گەورە دەبێتەوە؛ ڕاستییەکان دەتوانن بە نەرمی بچووکی بکەنەوە.",
      "لەرزی دۆخ بۆ زۆر شەپۆلی دڵەڕاوکێ کاتییە.",
      "دەتوانیت جەستە هێواش بکەیتەوە تەنانەت کاتێک بیرەکان سەرقاڵن.",
      "نادڵنیایی سەختە؛ وەک کارەسات نییە.",
      "پەنیک بەرز دەبێتەوە و دادەبەزێت — سواری یەک هەناسە یارمەتی دەدات.",
      "مامۆڵەت هەیە نیشانەی سەلامەتی لە ژوورەکەدا بخوازیت.",
      "ترس دەتوانێت بێت بەبێ خاوەندارێتی هەموو ئێوارەکە.",
      "سیستەمی دەمارەکەت دەتوانێت فێری «بۆ ئێستا بەسە» ببێت.",
      "ئارامی پێویست نییە بۆ هەنگاوێکی بچووک.",
    ],
  },
  {
    en: [
      "I can feel fear and still take the next small breath.",
      "This wave can pass. Right now, one slow exhale is enough.",
      "I don’t have to believe every urgent thought.",
      "I can name five things I see to come back to now.",
      "Safety can be built in tiny cues.",
      "I am allowed to slow down without having all answers.",
      "Worry is loud; I can answer softly.",
      "I can handle this minute, then the next.",
      "My body can settle even if my mind is noisy.",
      "I can ask for calm company if I need it.",
      "Uncertainty doesn’t mean I am unsafe right now.",
      "I can put one worry on a later list.",
      "I am here, in this room, breathing.",
      "Fear can ride beside me without driving.",
      "One grounded second counts.",
    ],
    ku: [
      "دەتوانم بترسم و هێشتا هەناسەی بچووکی داهاتوو هەڵبگرم.",
      "ئەم شەپۆلە تێدەپەڕێت. ئێستا یەک هەناسەی هێواش بەسە.",
      "پێویست ناکات باوەڕ بە هەموو بیری فریاگوزار بکەم.",
      "دەتوانم پێنج شت ناوببەم کە دەیانبینم بۆ گەڕانەوە بۆ ئێستا.",
      "سەلامەتی دەتوانێت بە نیشانەی بچووک دروست بکرێت.",
      "مامۆڵەم هەیە هێواش ببمەوە بەبێ هەموو وەڵامەکان.",
      "نیگەران بەرزە؛ دەتوانم بە نەرمی وەڵام بدەمەوە.",
      "دەتوانم ئەم خولەکە بەرگە بگرم، پاشان ئەوەی داهاتوو.",
      "جەستەم دەتوانێت ئارام ببێتەوە تەنانەت ئەگەر مێشکم دەنگدانەوەی هەبێت.",
      "دەتوانم داوای هاوڕێیەتی ئارام بکەم ئەگەر پێویست بێت.",
      "نادڵنیایی مانای ئەوە نییە ئێستا ناسیساتم.",
      "دەتوانم یەک نیگەرانی بخەمە لیستی دواتر.",
      "لێرەم، لەم ژوورەدا، هەناسە دەدەم.",
      "ترس دەتوانێت لە تەنیشتدا بێت بەبێ لێخوڕین.",
      "یەک چرکەی زەویکراو دەژمێردرێت.",
    ],
  },
  {
    en: [
      "Exhale longer than you inhale, four times.",
      "Press your feet into the floor and notice the pressure.",
      "Name 5 things you see, 4 you can touch.",
      "Hold something cool or warm and describe it silently.",
      "Step to a window and look at one distant point.",
      "Sip water slowly.",
      "Unclench your hands and drop your shoulders.",
      "Say out loud: “Right now, I am here.”",
      "Shorten the next task to two minutes only.",
      "If helpful, sit near someone safe without needing to talk.",
    ],
    ku: [
      "هەناسەدانەوە درێژتر لە هەناسەکێشان بکە، چوار جار.",
      "پێیەکانت لەسەر زەوی پاڵ بنێ و فشاری هەست پێ بکە.",
      "٥ شت ناوببە کە دەیانبینیت، ٤ شت کە دەستت لێیان دەدات.",
      "شتێکی سارد یان گەرم بگرە و بێدەنگ وەسفی بکە.",
      "بچۆ لای پەنجەرە و سەیری یەک خاڵی دوور بکە.",
      "ئاو بە هێواشی بخۆرەوە.",
      "دەستەکانت شل بکە و شانەکانت دابەزێنە.",
      "بە دەنگ بڵێ: «ئێستا، لێرەم.»",
      "ئەرکی داهاتوو تەنها بۆ دوو خولەک کورت بکەرەوە.",
      "ئەگەر یارمەتی دەدات، لە تەنیشت کەسێکی سەلامەت دانیشە بەبێ پێویستی قسە.",
    ],
  },
  {
    en: [
      "Fear can be loud without meaning danger is certain.",
      "One slow exhale is enough for this minute.",
      "You can ground in the room right now.",
      "Worry expands; one fact can shrink it.",
      "You can handle this minute, then the next.",
    ],
    ku: [
      "ترس دەتوانێت بەرز بێت بەبێ مانای مەترسی دڵنیا.",
      "یەک هەناسەی هێواش بۆ ئەم خولەکە بەسە.",
      "دەتوانیت ئێستا لە ژوورەکەدا زەوی بکەیت.",
      "نیگەران گەورە دەبێتەوە؛ یەک ڕاستی دەتوانێت بچووکی بکاتەوە.",
      "دەتوانیت ئەم خولەکە بەرگە بگریت، پاشان ئەوەی داهاتوو.",
    ],
  }
);

const guilt = cat(
  {
    en: [
      "Guilt is loud tonight. You’re not alone in that.",
      "I hear shame trying to take the whole story.",
      "You’re carrying “I should have” like a weight.",
      "Self-blame often arrives after care or conflict.",
      "It sounds like regret is sitting on your chest.",
      "You’re naming a painful sense of fault.",
      "Guilt can feel like proof — even when it overreaches.",
      "I hear the wish to undo something.",
      "You’re being hard on a past version of yourself.",
      "This remorse matters to you.",
    ],
    ku: [
      "هەستی گوناه ئەمشەو بەرزە. تۆ بە تەنها نیت لەمەدا.",
      "گوێم لە شەرمێکە دەیهەوێت هەموو چیرۆکەکە بگرێت.",
      "«دەبوو» وەک قورسییەک هەڵدەگریت.",
      "خۆسەرزنشت زۆرجار دوای چاودێری یان ناکۆکی دێت.",
      "وەک پەشیمانی لەسەر سنگت دانابێت.",
      "هەستی تاوانی ئازاربەخش ناودەبەیت.",
      "گوناه دەتوانێت وەک بەڵگە هەست پێ بکرێت — تەنانەت کاتێک زیادەڕەوی دەکات.",
      "گوێم لە ئارەزووی گەڕاندنەوەی شتێکە.",
      "سەختیت لەگەڵ وەشانی ڕابردووی خۆت.",
      "ئەم پەشیمانییە بۆت گرنگە.",
    ],
  },
  {
    en: [
      "You can learn without punishing yourself.",
      "Feeling guilty doesn’t automatically mean you are a bad person.",
      "Responsibility and self-destruction are different paths.",
      "A mistake can be repaired more easily than a self-attack.",
      "Shame shrinks growth; honest regret can guide repair.",
      "Past choices happened with the information you had then.",
      "You can make amends without erasing yourself.",
      "Guilt often overclaims credit for everything that went wrong.",
      "Being accountable can be quiet and specific.",
      "You deserve a path back that includes dignity.",
      "Not every heavy feeling is an accurate moral verdict.",
      "Growth includes imperfect apologies and better next tries.",
      "You can hold regret and still be worthy of rest.",
      "Self-blame is not the same as integrity.",
      "Repair starts with one clear, doable action.",
    ],
    ku: [
      "دەتوانیت فێر ببیت بەبێ سزادانی خۆت.",
      "هەستی گوناه خۆکار مانای کەسی خراپ بوونت نییە.",
      "بەرپرسیارێتی و خۆوێرانکردن ڕێگای جیاوازن.",
      "هەڵە ئاسانتر چاک دەبێتەوە لە هێرشی سەر خۆت.",
      "شەرم گەشە دەپەستێت؛ پەشیمانی ڕاستگۆ دەتوانێت چاککردنەوە ڕێنمایی بکات.",
      "هەڵبژاردنەکانی ڕابردوو لەگەڵ ئەو زانیارییە ڕوویاندا کە ئەوکات هەتبوو.",
      "دەتوانیت قەرەبوو بکەیتەوە بەبێ سڕینەوەی خۆت.",
      "گوناه زۆرجار خۆی بە خاوەنی هەموو خراپییەکان دەزانێت.",
      "بەرپرسیاربوون دەتوانێت بێدەنگ و دیاریکراو بێت.",
      "شایستەی ڕێگایەکی گەڕانەوەیت کە کەرامەتی تێدا بێت.",
      "هەموو هەستێکی قورس حوکمێکی ئەخلاقی ورد نییە.",
      "گەشە داوای لێبوردنی ناتەواو و هەوڵی باشتری داهاتوو دەکات.",
      "دەتوانیت پەشیمانی هەڵبگریت و هێشتا شایستەی پشوو بیت.",
      "خۆسەرزنشت وەک دەستپاکی نییە.",
      "چاککردنەوە بە یەک کرداری ڕوون و گونجاو دەست پێ دەکات.",
    ],
  },
  {
    en: [
      "I can learn without punishing myself.",
      "I can repair one specific thing without attacking my whole self.",
      "Regret can guide me; shame doesn’t have to own me.",
      "I am allowed to grow from this.",
      "I can apologize or adjust where it’s possible.",
      "My worth isn’t cancelled by a mistake.",
      "I can choose accountability that is kind and clear.",
      "I don’t have to carry endless self-blame to be good.",
      "I can rest while I plan a repair.",
      "One better choice tomorrow still counts.",
      "I can forgive the part of me that didn’t know yet.",
      "I am more than this regret.",
      "I can make a small amends today.",
      "Integrity includes care for myself too.",
      "I can hold the lesson without the cruelty.",
    ],
    ku: [
      "دەتوانم فێر ببم بەبێ سزادانی خۆم.",
      "دەتوانم یەک شتی دیاریکراو چاک بکەمەوە بەبێ هێرشکردنە سەر هەموو خۆم.",
      "پەشیمانی دەتوانێت ڕێنمایی بکات؛ شەرم پێویست ناکات خاوەنم بێت.",
      "مامۆڵەم هەیە لەمە گەشە بکەم.",
      "دەتوانم داوای لێبوردن یان گۆڕان بکەم لەوێی کە گونجاوە.",
      "بەهایم بە هەڵەیەک هەڵناوەشێتەوە.",
      "دەتوانم بەرپرسیارێتی میهرەبان و ڕوون هەڵبژێرم.",
      "پێویست ناکات خۆسەرزنشتی بێکۆتایی هەڵبگرم بۆ باش بوون.",
      "دەتوانم پشوو بدەم کاتێک پلانی چاککردنەوە دادەنێم.",
      "یەک هەڵبژاردەی باشتر سبەینێ هێشتا دەژمێردرێت.",
      "دەتوانم ئەو بەشەم لێببورم کە هێشتا نەیەزانی.",
      "من زیاترم لەم پەشیمانییە.",
      "دەتوانم ئەمڕۆ قەرەبوویەکی بچووک بکەمەوە.",
      "دەستپاکی چاودێری خۆیشی تێدایە.",
      "دەتوانم وانەکە هەڵبگرم بەبێ توندی.",
    ],
  },
  {
    en: [
      "Write one specific repair action you can do this week.",
      "If an apology helps, keep it short and sincere.",
      "Separate “what I did” from “what I am.”",
      "Do one kind act that aligns with your values.",
      "Talk to a trusted person about the facts only.",
      "Schedule the repair, then allow rest.",
      "Replace one shaming sentence with a learning sentence.",
      "Return a message or item if that’s part of amends.",
      "Sit with the feeling for two minutes without spiraling.",
      "Choose dignity: repair, then stop the self-attack.",
    ],
    ku: [
      "یەک کرداری چاککردنەوەی دیاریکراو بنووسە کە ئەم هەفتەیە بیکەیت.",
      "ئەگەر داوای لێبوردن یارمەتی دەدات، کورت و دڵسۆز بیهێڵەرەوە.",
      "«ئەوەی کردم» لە «ئەوەی هەم» جیا بکەرەوە.",
      "یەک کرداری میهرەبان بکە کە لەگەڵ بەهاکانت بگونجێت.",
      "تەنها لەسەر ڕاستییەکان قسە لەگەڵ کەسێکی متمانەپێکراو بکە.",
      "چاککردنەوە دیاری بکە، پاشان پشوو ڕێگە پێ بدە.",
      "یەک ڕستەی شەرم بە ڕستەی فێربوون بگۆڕە.",
      "پەیام یان شتێک بگەڕێنەرەوە ئەگەر بەشێک لە قەرەبووە.",
      "دوو خولەک لەگەڵ هەستەکە دانیشە بەبێ سووڕانەوە.",
      "کەرامەت هەڵبژێرە: چاک بکەرەوە، پاشان هێرشی سەر خۆت بوەستێنە.",
    ],
  },
  {
    en: [
      "You can learn without punishing yourself.",
      "Guilt isn’t always an accurate verdict.",
      "Repair one specific thing with dignity.",
      "Regret can guide; shame doesn’t have to own you.",
      "Your worth isn’t cancelled by a mistake.",
    ],
    ku: [
      "دەتوانیت فێر ببیت بەبێ سزادانی خۆت.",
      "گوناه هەمیشە حوکمێکی ورد نییە.",
      "یەک شتی دیاریکراو بە کەرامەت چاک بکەرەوە.",
      "پەشیمانی دەتوانێت ڕێنمایی بکات؛ شەرم پێویست ناکات خاوەنت بێت.",
      "بەهایت بە هەڵەیەک هەڵناوەشێتەوە.",
    ],
  }
);

const anger = cat(
  {
    en: [
      "Anger is present — something important feels crossed.",
      "I hear heat in these words.",
      "Frustration can build when limits aren’t respected.",
      "You’re naming a real sense of unfairness.",
      "Rage often protects a softer hurt underneath.",
      "It sounds like you’ve been holding this in.",
      "Irritation is loud in your system right now.",
      "You’re reacting to something that matters to you.",
      "I hear the wish for things to be different.",
      "This anger deserves to be heard without shame.",
    ],
    ku: [
      "تووڕەیی ئامادەیە — شتێکی گرنگ پێشێلکراو هەست دەکات.",
      "گوێم لە گەرمی لەم وشانه دا.",
      "بێزاری دروست دەبێت کاتێک سنوورەکان ڕێزیان لێ ناگیرێت.",
      "هەستی نادادپەروەری ڕاستەقینە ناودەبەیت.",
      "قین زۆرجار ئازارێکی نەرمتری ژێرەوە دەپارێزێت.",
      "وەک ئەوەی ئەمەت لەناو خۆتدا هەڵگرتبێت.",
      "بێزاری لە سیستەمەکەتدا بەرزە ئێستا.",
      "کاردانەوەت بەرامبەر شتێکە کە بۆت گرنگە.",
      "گوێم لە ئارەزووی جیاوازبوونی شتەکانە.",
      "ئەم تووڕەییە شایستەی بیستنە بەبێ شەرم.",
    ],
  },
  {
    en: [
      "Anger can be information about a boundary, not proof you’re “bad.”",
      "Feeling furious doesn’t require acting on every impulse.",
      "You can honor the anger and still choose a safer next step.",
      "Heat in the body is real; cruelty doesn’t have to follow.",
      "Naming the unfairness can reduce the spiral.",
      "Anger often arrives when care or respect felt missing.",
      "You can pause without dismissing what hurt you.",
      "Strong feelings can coexist with careful action.",
      "Being fed up is human after repeated strain.",
      "You don’t have to explode or disappear — a middle path exists.",
      "Anger can point to a need: space, respect, or clarity.",
      "You can cool the body while keeping the message.",
      "Not every conflict needs an immediate reaction.",
      "Your anger can be taken seriously without becoming harm.",
      "Feeling mad and staying in control can both be true.",
    ],
    ku: [
      "تووڕەیی دەتوانێت زانیاری بێت لەسەر سنوور، نەک بەڵگەی «خراپ» بوونت.",
      "هەستی قین پێویستی بە جێبەجێکردنی هەموو پاڵنەرێک نییە.",
      "دەتوانیت ڕێز لە تووڕەیی بگریت و هێشتا هەنگاوێکی سەلامەتتر هەڵبژێریت.",
      "گەرمی لە جەستەدا ڕاستەقینەیە؛ توندی پێویست ناکات دوای بێت.",
      "ناونانی نادادپەروەری دەتوانێت سووڕانەوە کەم بکاتەوە.",
      "تووڕەیی زۆرجار دێت کاتێک چاودێری یان ڕێز کەم هەست کرا.",
      "دەتوانیت بوەستیت بەبێ پشتگوێخستنی ئەوەی برینداری کردیت.",
      "هەستی بەهێز دەتوانێت لەگەڵ کرداری وریا پێکەوە بن.",
      "بێزاربوون مرۆڤایەتییە دوای فشاری دووبارە.",
      "پێویست ناکات بتەقێیتەوە یان ون بیت — ڕێگای ناوەند هەیە.",
      "تووڕەیی دەتوانێت ئاماژە بە پێویستی بکات: بۆشایی، ڕێز، یان ڕوونی.",
      "دەتوانیت جەستە فێنک بکەیتەوە و پەیامەکە بهێڵیتەوە.",
      "هەموو ناکۆکییەک پێویستی بە کاردانەوەی یەکسەر نییە.",
      "تووڕەییەکەت دەتوانێت بە جددی بگیرێت بەبێ بوون بە زیان.",
      "تووڕەبوون و لە کۆنترۆڵدا مانەوە دەتوانن هەردووکیان ڕاست بن.",
    ],
  },
  {
    en: [
      "I can feel this anger and still choose a safer next move.",
      "My anger points to something that mattered.",
      "I can cool my body before I decide what to say.",
      "I don’t have to act on the hottest impulse.",
      "I can set a boundary without becoming cruel.",
      "This heat can pass while I stay grounded.",
      "I am allowed to want respect.",
      "I can write the anger first, send later if needed.",
      "I can take space without disappearing forever.",
      "Strong feeling, careful action.",
      "I can protect myself and still stay human.",
      "I don’t owe anyone an explosion.",
      "I can name the need under the anger.",
      "Pause is strength when I’m heated.",
      "I can return to this when I’m steadier.",
    ],
    ku: [
      "دەتوانم ئەم تووڕەییە هەست پێ بکەم و هێشتا جووڵەی سەلامەتتر هەڵبژێرم.",
      "تووڕەییەکەم ئاماژە بە شتێک دەکات کە گرنگ بوو.",
      "دەتوانم جەستەم فێنک بکەمەوە پێش بڕیار لەسەر قسە.",
      "پێویست ناکات بە گەرمترین پاڵنەر هەڵسوکەوت بکەم.",
      "دەتوانم سنوور دابنێم بەبێ بوون بە توند.",
      "ئەم گەرمییە دەتوانێت تێپەڕێت کاتێک زەویکراو دەمێنمەوە.",
      "مامۆڵەم هەیە ڕێز بخوازم.",
      "دەتوانم یەکەم تووڕەیی بنووسم، دواتر بنێرم ئەگەر پێویست بوو.",
      "دەتوانم بۆشایی وەربگرم بەبێ ونبوونی هەمیشەیی.",
      "هەستی بەهێز، کرداری وریا.",
      "دەتوانم خۆم بپارێزم و هێشتا مرۆڤ بمێنمەوە.",
      "قەرزاری کەس نیم بتەقێمەوە.",
      "دەتوانم پێویستی ژێر تووڕەیی ناوببەم.",
      "وەستان هێزە کاتێک گەرمم.",
      "دەتوانم بگەڕێمەوە بۆ ئەمە کاتێک جێگیرترم.",
    ],
  },
  {
    en: [
      "Step away for two minutes before responding.",
      "Shake out your hands and exhale hard once.",
      "Write the unsent message, then wait ten minutes.",
      "Name the boundary in one calm sentence.",
      "Splash cool water on your wrists.",
      "Walk a short loop if you can.",
      "Put the conflict on pause until you’re steadier.",
      "Ask for space: “I need a moment.”",
      "Channel the heat into a physical release that isn’t harm.",
      "Return only when you can speak without aiming to hurt.",
    ],
    ku: [
      "پێش وەڵامدانەوە دوو خولەک دوور بکەوەرەوە.",
      "دەستەکانت بجووڵێنە و یەک جار بەهێز هەناسە بدەرەوە.",
      "پەیامی نەنێردراو بنووسە، پاشان دە خولەک چاوەڕێ بکە.",
      "سنوورەکە لە یەک ڕستەی ئارامدا ناوببە.",
      "ئاوی فێنک بە مەچەکەکانتدا بهێنە.",
      "ئەگەر دەتوانیت، خولێکی کورت بڕۆ.",
      "ناکۆکییەکە بوەستێنە تا جێگیرتر دەبیت.",
      "داوای بۆشایی بکە: «پێویستیم بە کاتێکە.»",
      "گەرمییەکە بگۆڕە بۆ دەرهاویشتنی جەستەیی کە زیان نییە.",
      "تەنها بگەڕێوە کاتێک دەتوانیت قسە بکەیت بەبێ مەبەستی ئازاردان.",
    ],
  },
  {
    en: [
      "Anger can be a boundary signal, not a verdict on your character.",
      "You can cool your body before you decide.",
      "Strong feeling, careful next step.",
      "You are allowed to want respect.",
      "Pause can be strength when you’re heated.",
    ],
    ku: [
      "تووڕەیی دەتوانێت ئاماژەی سنوور بێت، نەک حوکم لەسەر کەسایەتیت.",
      "دەتوانیت جەستە فێنک بکەیتەوە پێش بڕیار.",
      "هەستی بەهێز، هەنگاوی وریای داهاتوو.",
      "مامۆڵەت هەیە ڕێز بخوازیت.",
      "وەستان دەتوانێت هێز بێت کاتێک گەرمی.",
    ],
  }
);

const hopelessness = cat(
  {
    en: [
      "Hopelessness can flatten everything into “what’s the point.”",
      "I hear how heavy the future feels.",
      "You’re describing a fog where options disappear.",
      "It sounds like hope got quiet.",
      "This emptiness of meaning is painful.",
      "You’re tired of trying without relief.",
      "I hear despair asking to be acknowledged.",
      "When nothing feels movable, the mind shuts doors.",
      "You’re naming a deep low.",
      "This weight deserves gentleness, not pressure to cheer up.",
    ],
    ku: [
      "بێهیوایی دەتوانێت هەموو شت تەخت بکاتەوە بۆ «چی مانای هەیە».",
      "گوێم لەوەیە داهاتوو چەند قورس هەست دەکات.",
      "تەمێک وەسف دەکەیت کە هەڵبژاردنەکان تێیدا ون دەبن.",
      "وەک هیوا بێدەنگ بووبێت.",
      "ئەم بەتاڵی مانایە ئازاربەخشە.",
      "ماندوویت لە هەوڵدان بەبێ سووکبوونەوە.",
      "گوێم لە نائومێدییەکە داوای ناسین دەکات.",
      "کاتێک هیچ شت جووڵاو نابێت، مێشک دەرگا دادەخات.",
      "نزمێکی قووڵ ناودەبەیت.",
      "ئەم قورسییە شایستەی نەرمییە، نەک فشاری خۆشبینبوون.",
    ],
  },
  {
    en: [
      "Feeling hopeless now doesn’t prove nothing can ever change.",
      "Foggy days hide options that still exist outside the fog.",
      "You don’t have to see the whole path to take one step.",
      "Low hope is a state; it isn’t always a permanent map.",
      "Small changes can matter even when big ones feel impossible.",
      "Despair exaggerates forever; the present can still hold a tiny next.",
      "You can borrow a little structure when motivation is gone.",
      "Not feeling point doesn’t mean you are pointless.",
      "Energy for hope often returns after rest and support.",
      "You can survive a numb hour without solving life tonight.",
      "Meaning can be rebuilt in small, boring, kind acts.",
      "A closed feeling is not the same as a closed future.",
      "You deserve help when the dark feels thick.",
      "One caring action can coexist with hopeless thoughts.",
      "This chapter can be heavy without being the ending.",
    ],
    ku: [
      "هەستی بێهیوایی ئێستا بەڵگە نییە کە هەرگیز هیچ ناگۆڕێت.",
      "ڕۆژە تەمئاویەکان هەڵبژاردن دەشارنەوە کە هێشتا لە دەرەوەی تەمەکە هەن.",
      "پێویست ناکات هەموو ڕێگا ببینیت بۆ هەڵگرتنی یەک هەنگاو.",
      "هیوای نزم دۆخێکە؛ هەمیشە نەخشەی هەمیشەیی نییە.",
      "گۆڕانکاری بچووک دەتوانێت گرنگ بێت تەنانەت کاتێک گەورەکان مەحاڵ هەست دەکەن.",
      "نائومێدی هەمیشەیی گەورە دەکات؛ ئێستا هێشتا دەتوانێت هەنگاوێکی بچووک هەڵبگرێت.",
      "دەتوانیت کەمێک پێکهاتە قەرز بکەیت کاتێک هاندەر نەماوە.",
      "هەستی بێمانایی مانای بێمانا بوونت نییە.",
      "وزە بۆ هیوا زۆرجار دوای پشوو و پشتگیری دەگەڕێتەوە.",
      "دەتوانیت کاتژمێرێکی بێهەست بەرگە بگریت بەبێ چارەسەرکردنی ژیان ئەمشەو.",
      "مانا دەتوانێت بە کرداری بچووک، بێزارکەر، میهرەبان دوبارە دروست بکرێتەوە.",
      "هەستی داخراو وەک داهاتووی داخراو نییە.",
      "شایستەی یارمەتیت کاتێک تاریکی ئەستوور هەست دەکات.",
      "یەک کرداری چاودێری دەتوانێت لەگەڵ بیری بێهیوایی پێکەوە بێت.",
      "ئەم بەشە دەتوانێت قورس بێت بەبێ بوون بە کۆتایی.",
    ],
  },
  {
    en: [
      "I don’t have to see the whole path — one small step is enough.",
      "This fog can lift; I can move gently meanwhile.",
      "Hopeless feelings can visit without owning forever.",
      "I can ask for support when the dark feels thick.",
      "I am allowed to rest inside a hard chapter.",
      "A tiny kind act still counts today.",
      "I can survive this hour.",
      "Meaning can return slowly.",
      "I don’t have to force cheer to stay alive to the next minute.",
      "I can hold on without pretending I’m fine.",
      "One boring useful action is enough for now.",
      "I can borrow hope from a trusted person briefly.",
      "This low is real; it may not be permanent.",
      "I can choose the next kind thing, not the whole future.",
      "I matter even when hope is quiet.",
    ],
    ku: [
      "پێویست ناکات هەموو ڕێگا ببینم — یەک هەنگاوی بچووک بەسە.",
      "ئەم تەمە دەتوانێت هەڵکەوێت؛ لە نێواندا بە نەرمی دەجووڵێم.",
      "هەستی بێهیوایی دەتوانێت بێت بەبێ خاوەندارێتی هەمیشەیی.",
      "دەتوانم یارمەتی بخوازم کاتێک تاریکی ئەستوورە.",
      "مامۆڵەم هەیە لەناو بەشێکی قورسدا پشوو بدەم.",
      "یەک کرداری میهرەبانی بچووک ئەمڕۆ هێشتا دەژمێردرێت.",
      "دەتوانم ئەم کاتژمێرە بەرگە بگرم.",
      "مانا دەتوانێت هێواش بگەڕێتەوە.",
      "پێویست ناکات خۆشبینی زۆرەملێ بکەم بۆ مانەوە تا خولەکی داهاتوو.",
      "دەتوانم خۆم بگرم بەبێ پیشاندانی کە باشم.",
      "یەک کرداری بێزارکەری بەسوود بۆ ئێستا بەسە.",
      "دەتوانم کەمێک هیوا لە کەسێکی متمانەپێکراو قەرز بکەم.",
      "ئەم نزمە ڕاستەقینەیە؛ ڕەنگە هەمیشەیی نەبێت.",
      "دەتوانم شتی میهرەبانی داهاتوو هەڵبژێرم، نەک هەموو داهاتوو.",
      "گرنگم تەنانەت کاتێک هیوا بێدەنگە.",
    ],
  },
  {
    en: [
      "Do one tiny useful act: water, wash face, or open a window.",
      "Text someone safe: “Having a hard hour.”",
      "Sit outside or by a window for three minutes.",
      "Reduce tonight’s goals to one item only.",
      "Put on a calm sound and stay with it briefly.",
      "Write “I only need the next hour” on paper.",
      "Ask for practical help with one task.",
      "Lie down and count ten slow breaths.",
      "Eat something simple if energy is gone.",
      "Keep company nearby if solitude makes the fog thicker.",
    ],
    ku: [
      "یەک کرداری بچووکی بەسوود: ئاو، شوشتنی ڕووخسار، یان کردنەوەی پەنجەرە.",
      "بۆ کەسێکی سەلامەت بنووسە: «کاتژمێرێکی قورسم هەیە.»",
      "سێ خولەک لە دەرەوە یان لای پەنجەرە دانیشە.",
      "ئامانجەکانی ئەمشەو تەنها بۆ یەک شت کەم بکەرەوە.",
      "دەنگێکی ئارام لێبدە و کەمێک لەگەڵی بمێنەرەوە.",
      "لەسەر کاغەز بنووسە «تەنها پێویستیم بە کاتژمێری داهاتووە».",
      "داوای یارمەتی کرداری بۆ یەک ئەرک بکە.",
      "ڕاکەشە و دە هەناسەی هێواش بژمێرە.",
      "ئەگەر وزە نەماوە شتێکی سادە بخۆ.",
      "ئەگەر تەنیایی تەمەکە ئەستوورتر دەکات، کەسێک لە نزیک بهێڵەرەوە.",
    ],
  },
  {
    en: [
      "You don’t need the whole path — one small step is enough.",
      "Hopeless feelings can visit without owning forever.",
      "A tiny kind act still counts.",
      "This chapter can be heavy without being the ending.",
      "You matter even when hope is quiet.",
    ],
    ku: [
      "پێویستت بە هەموو ڕێگا نییە — یەک هەنگاوی بچووک بەسە.",
      "هەستی بێهیوایی دەتوانێت بێت بەبێ خاوەندارێتی هەمیشەیی.",
      "یەک کرداری میهرەبانی بچووک هێشتا دەژمێردرێت.",
      "ئەم بەشە دەتوانێت قورس بێت بەبێ بوون بە کۆتایی.",
      "گرنگیت تەنانەت کاتێک هیوا بێدەنگە.",
    ],
  }
);

const overthinking = cat(
  {
    en: [
      "Your mind won’t stop — that mental noise is exhausting.",
      "I hear thoughts looping without landing.",
      "Overthinking can feel like being stuck inside your head.",
      "You’re describing a busy mind that won’t rest.",
      "Rumination is loud tonight.",
      "It sounds hard to step out of the spiral.",
      "Thinking too much can masquerade as problem-solving.",
      "I hear the strain of mental spinning.",
      "Your thoughts are racing ahead of calm.",
      "This mental stuckness deserves a softer pace.",
    ],
    ku: [
      "مێشکت ڕاناوەستێت — ئەم دەنگدانەوەیە ماندووکەرە.",
      "گوێم لە بیرەکانە کە دەسوڕێنەوە بەبێ نیشتن.",
      "زۆر بیرکردنەوە دەتوانێت وەک قەتیسبوون لەناو سەرت هەست پێ بکرێت.",
      "مێشکێکی سەرقاڵ وەسف دەکەیت کە پشوو نادات.",
      "دووبارە بیرکردنەوە ئەمشەو بەرزە.",
      "سەختە لە سووڕانەوە دەرچیت.",
      "زۆر بیرکردنەوە دەتوانێت خۆی وەک چارەسەرکردن پیشان بدات.",
      "گوێم لە فشاری سووڕانی مێشکە.",
      "بیرەکانت پێش ئارامی ڕادەکەن.",
      "ئەم قەتیسبوونە مێشکییە شایستەی خێراییەکی نەرمترە.",
    ],
  },
  {
    en: [
      "Thinking hard isn’t the same as finding clarity.",
      "A looping mind often needs grounding more than more analysis.",
      "You can park a thought without solving it tonight.",
      "Mental noise can quiet when the body slows.",
      "Not every question needs an answer before sleep.",
      "Overthinking exaggerates urgency.",
      "You can choose a container for worries: later, not never.",
      "Resting the mind is a skill, not a failure of intelligence.",
      "Spirals shrink when attention returns to the senses.",
      "You don’t have to finish the debate in your head tonight.",
      "Thoughts can wait while you take one physical step.",
      "Clarity often arrives after a pause, not during a storm.",
      "You can be thoughtful without being trapped.",
      "One written line can stop a ten-minute loop.",
      "Your mind deserves breaks like any tired muscle.",
    ],
    ku: [
      "قورس بیرکردنەوە وەک دۆزینەوەی ڕوونی نییە.",
      "مێشکی سووڕاو زۆرجار پێویستی بە گەڕانەوە بۆ ئێستا هەیە زیاتر لە شیکاری زیاتر.",
      "دەتوانیت بیرێک دابنێیت بەبێ چارەسەرکردنی ئەمشەو.",
      "دەنگدانەوەی مێشک دەتوانێت کەم ببێتەوە کاتێک جەستە هێواش دەبێتەوە.",
      "هەموو پرسیارێک پێویستی بە وەڵام نییە پێش خەو.",
      "زۆر بیرکردنەوە فریاگوزاری گەورە دەکات.",
      "دەتوانیت دەفرێک بۆ نیگەرانییەکان هەڵبژێریت: دواتر، نەک هەرگیز.",
      "پشوودانی مێشک لێهاتوویییە، نەک شکستی زیر.",
      "سووڕانەوەکان بچووک دەبنەوە کاتێک سەرنج دەگەڕێتەوە بۆ هەستەکان.",
      "پێویست ناکات ئەمشەو گفتوگۆی ناو سەرت تەواو بکەیت.",
      "بیرەکان دەتوانن چاوەڕێ بکەن کاتێک یەک هەنگاوی جەستەیی دەگریت.",
      "ڕوونی زۆرجار دوای وەستان دێت، نەک لەناو زریاندا.",
      "دەتوانیت بیرکەرەوە بیت بەبێ قەتیسبوون.",
      "یەک هێڵی نووسراو دەتوانێت سووڕانەوەی دە خولەک بوەستێنێت.",
      "مێشکت شایستەی پشووە وەک هەر ماسوولکەیەکی ماندوو.",
    ],
  },
  {
    en: [
      "I can park this thought and return later.",
      "I don’t have to solve everything in my head tonight.",
      "One breath, then one sensory detail.",
      "My mind can rest without finishing the loop.",
      "I can write it down and close the page.",
      "Thinking can wait while I ground.",
      "I am allowed to interrupt the spiral kindly.",
      "Clarity can come after quiet.",
      "I can choose “later” for this worry.",
      "Stuck thoughts don’t have to run the evening.",
      "I can move my body to move my mind.",
      "Soft attention is enough right now.",
      "I can stop analyzing for five minutes.",
      "My worth isn’t tied to endless thinking.",
      "I can be done for now.",
    ],
    ku: [
      "دەتوانم ئەم بیرە دابنێم و دواتر بگەڕێمەوە.",
      "پێویست ناکات ئەمشەو هەموو شت لە سەرمدا چارەسەر بکەم.",
      "یەک هەناسە، پاشان یەک وردەکاری هەستی.",
      "مێشکم دەتوانێت پشوو بدات بەبێ تەواوکردنی سووڕانەوە.",
      "دەتوانم بینووسم و پەڕەکە دابخەم.",
      "بیرکردنەوە دەتوانێت چاوەڕێ بکات کاتێک زەوی دەکەم.",
      "مامۆڵەم هەیە سووڕانەوە بە میهرەبانی ببڕم.",
      "ڕوونی دەتوانێت دوای بێدەنگی بێت.",
      "دەتوانم «دواتر» بۆ ئەم نیگەرانییە هەڵبژێرم.",
      "بیری قەتیس پێویست ناکات ئێوارەکە بەڕێوەببات.",
      "دەتوانم جەستە بجووڵێنم بۆ جووڵاندنی مێشک.",
      "سەرنجی نەرم ئێستا بەسە.",
      "دەتوانم پێنج خولەک شیکاری بوەستێنم.",
      "بەهایم بە بیرکردنەوەی بێکۆتایی بەستراو نییە.",
      "دەتوانم بۆ ئێستا تەواو بم.",
    ],
  },
  {
    en: [
      "Write the looping thought once, then close the notebook.",
      "Name three sounds in the room.",
      "Do a two-minute body stretch.",
      "Set a “worry window” for tomorrow, not now.",
      "Wash your hands slowly and notice the water.",
      "Change rooms for a short reset.",
      "Put your phone face-down for ten minutes.",
      "Say: “Not tonight — later.”",
      "Count backward from 30 while walking slowly.",
      "Choose one sensory anchor: scent, texture, or light.",
    ],
    ku: [
      "بیری سووڕاو یەک جار بنووسە، پاشان دەفتەرەکە دابخە.",
      "سێ دەنگ لە ژوورەکەدا ناوببە.",
      "درێژکردنەوەی جەستە بۆ دوو خولەک بکە.",
      "«پەنجەرەی نیگەرانی» بۆ سبەینێ دابنێ، نەک ئێستا.",
      "دەستەکانت هێواش بشۆ و ئاوی هەست پێ بکە.",
      "بۆ ڕیسێتی کورت ژوور بگۆڕە.",
      "دە خولەک مۆبایل ڕوو لە خوارەوە دابنێ.",
      "بڵێ: «نەک ئەمشەو — دواتر.»",
      "لە ٣٠ەوە بژمێرەوە کاتێک هێواش دەڕۆیت.",
      "یەک لنکەری هەستی هەڵبژێرە: بۆن، دەستلێدان، یان ڕووناکی.",
    ],
  },
  {
    en: [
      "You can park the thought without solving it tonight.",
      "A looping mind needs grounding more than more analysis.",
      "One breath, then one sensory detail.",
      "You are allowed to interrupt the spiral kindly.",
      "Your mind deserves a break.",
    ],
    ku: [
      "دەتوانیت بیرەکە دابنێیت بەبێ چارەسەرکردنی ئەمشەو.",
      "مێشکی سووڕاو پێویستی بە گەڕانەوە بۆ ئێستا هەیە زیاتر لە شیکاری زیاتر.",
      "یەک هەناسە، پاشان یەک وردەکاری هەستی.",
      "مامۆڵەت هەیە سووڕانەوە بە میهرەبانی ببڕیت.",
      "مێشکت شایستەی پشووە.",
    ],
  }
);

const rejection = cat(
  {
    en: [
      "Being ignored or turned away can cut deeply.",
      "I hear the sting of not being chosen in this moment.",
      "Rejection often wakes older fears of not mattering.",
      "You’re naming a real social wound.",
      "It sounds like distance from someone hurt.",
      "Feeling pushed away is heavy.",
      "I hear the ache after someone left or went quiet.",
      "This silence from them feels personal.",
      "You’re carrying the weight of being set aside.",
      "Unanswered care can feel like proof — even when it isn’t complete proof.",
    ],
    ku: [
      "پشتگوێخستن یان ڕەتکردنەوە دەتوانێت قووڵ ببڕێت.",
      "گوێم لە ئازاری هەڵنەبژێردراو بوون لەم کاتەدا.",
      "ڕەتکردنەوە زۆرجار ترسی کۆنتری «گرنگ نەبوون» بیدار دەکاتەوە.",
      "برینێکی کۆمەڵایەتی ڕاستەقینە ناودەبەیت.",
      "وەک دووری لە کەسێک برینداری کردبێت.",
      "هەستی دوورخستنەوە قورسە.",
      "گوێم لە ئازار دوای جێهێشتن یان بێدەنگبوونی کەسێک.",
      "ئەم بێدەنگییەی ئەوان کەسی هەست دەکات.",
      "قورسی وەلاونان هەڵدەگریت.",
      "چاودێری بێ وەڵام دەتوانێت وەک بەڵگە هەست پێ بکرێت — تەنانەت کاتێک بەڵگەی تەواو نییە.",
    ],
  },
  {
    en: [
      "One person’s distance is not a full measure of your lovability.",
      "Being ignored hurts; it doesn’t always mean you are unwanted by everyone.",
      "Rejection can be about their capacity, timing, or limits — not only about you.",
      "You can grieve the connection without erasing your worth.",
      "Silence stings; it isn’t always a final definition of you.",
      "You deserved clearer care than this moment offered.",
      "Feeling rejected is human after reaching out.",
      "Not being chosen here doesn’t cancel every bond elsewhere.",
      "You can protect your heart and still stay open carefully later.",
      "Their quiet is data about this relationship, not your entire value.",
      "You are allowed to want reciprocity.",
      "Pain after rejection can fade without forcing fake confidence.",
      "You can take space to recover dignity.",
      "One cold response isn’t the whole social world.",
      "Your need for respect is valid.",
    ],
    ku: [
      "دووری یەک کەس پێوانەی تەواوی شایستەیی خۆشەویستیت نییە.",
      "پشتگوێخستن دەئێشێت؛ هەمیشە مانای نەخوازراو بوونت لەلای هەمووان نییە.",
      "ڕەتکردنەوە دەتوانێت دەربارەی توانا، کات، یان سنووری ئەوان بێت — نەک تەنها دەربارەی تۆ.",
      "دەتوانیت بۆ پەیوەندییەکە خەمگین بیت بەبێ سڕینەوەی بەهایت.",
      "بێدەنگی دەئێشێت؛ هەمیشە پێناسەی کۆتایی تۆ نییە.",
      "شایستەی چاودێری ڕوونتر بوویت لەوەی ئەم کاتە پێشکەشی کرد.",
      "هەستی ڕەتکردنەوە مرۆڤایەتییە دوای دەستپێڕاگەیشتن.",
      "لێرە هەڵنەبژێردراو بوون هەموو پەیوەندی تر هەڵناوەشێتەوە.",
      "دەتوانیت دڵت بپارێزیت و هێشتا دواتر بە وریایی کراوە بیت.",
      "بێدەنگییان زانیارییە لەسەر ئەم پەیوەندییە، نەک هەموو بەهایت.",
      "مامۆڵەت هەیە هاوسەنگی بخوازیت.",
      "ئازاری دوای ڕەتکردنەوە دەتوانێت کەم ببێتەوە بەبێ متمانەی ساختە.",
      "دەتوانیت بۆشایی وەربگریت بۆ گەڕاندنەوەی کەرامەت.",
      "یەک وەڵامی سارد هەموو جیهانی کۆمەڵایەتی نییە.",
      "پێویستیت بە ڕێز ڕەوایە.",
    ],
  },
  {
    en: [
      "I can hurt from this without concluding I am unlovable.",
      "Their distance is about this moment, not my entire worth.",
      "I deserve reciprocal care.",
      "I can take space to recover.",
      "I am allowed to want clearer respect.",
      "One rejection doesn’t erase every connection.",
      "I can protect my heart kindly.",
      "I matter even when someone goes quiet.",
      "I can grieve and still keep dignity.",
      "I don’t have to chase to prove my value.",
      "I can choose safer closeness next.",
      "This sting can soften with time and care.",
      "I am more than this unanswered reach.",
      "I can ask for what I need, or step back.",
      "My worth stays while I heal.",
    ],
    ku: [
      "دەتوانم لەمە بئێشم بەبێ ئەنجامگیری کە ناتوانم خۆشەویست بم.",
      "دوورییان دەربارەی ئەم کاتەیە، نەک هەموو بەهایم.",
      "شایستەی چاودێری هاوسەنگم.",
      "دەتوانم بۆشایی وەربگرم بۆ چاکبوونەوە.",
      "مامۆڵەم هەیە ڕێزی ڕوونتر بخوازم.",
      "یەک ڕەتکردنەوە هەموو پەیوەندی ناسڕێتەوە.",
      "دەتوانم دڵم بە میهرەبانی بپارێزم.",
      "گرنگم تەنانەت کاتێک کەسێک بێدەنگ دەبێت.",
      "دەتوانم خەمگین بم و هێشتا کەرامەت بهێڵمەوە.",
      "پێویست ناکات ڕاوەدوو بکەوم بۆ سەلماندنی بەهایم.",
      "دەتوانم نزیکبوونەوەی سەلامەتتر هەڵبژێرم دواتر.",
      "ئەم ئازارە دەتوانێت بە کات و چاودێری نەرم ببێتەوە.",
      "من زیاترم لەم دەستپێڕاگەیشتنە بێ وەڵامە.",
      "دەتوانم داوای پێویستیم بکەم، یان هەنگاو بۆ دواوە بنێم.",
      "بەهایم دەمێنێتەوە کاتێک چاک دەبمەوە.",
    ],
  },
  {
    en: [
      "Write what you needed in one sentence, for yourself.",
      "Pause contact for a cooling window if you’re spiraling.",
      "Do one self-respect action: meal, shower, or tidy corner.",
      "Talk to someone who already shows care.",
      "Put the phone down for twenty minutes.",
      "Name three people or places where you have belonged.",
      "Choose not to reread the painful thread tonight.",
      "Plan a small comfort for your evening.",
      "If you respond, keep it short and boundaried.",
      "Rest your heart before deciding the next social step.",
    ],
    ku: [
      "ئەوەی پێویستت بوو لە یەک ڕستەدا بۆ خۆت بنووسە.",
      "ئەگەر دەسوڕێیتەوە، پەیوەندی بۆ ماوەیەک بوەستێنە.",
      "یەک کرداری ڕێزی خۆت: خواردن، حەمام، یان ڕێکخستنی گۆشەیەک.",
      "قسە لەگەڵ کەسێک بکە کە پێشتر چاودێری پیشان دەدات.",
      "بیست خولەک مۆبایل دابنێ.",
      "سێ کەس یان شوێن ناوببە کە تێیدا هەستی سەر بە شوێنت هەبووە.",
      "بڕیار بدە ئەمشەو دووبارە خوێندنەوەی گفتوگۆی ئازاربەخش نەکەیت.",
      "ئارامییەکی بچووک بۆ ئێوارەکەت پلانی بۆ دابنێ.",
      "ئەگەر وەڵام دەدەیتەوە، کورت و سنووردار بیهێڵەرەوە.",
      "دڵت پشوو بدە پێش بڕیار لەسەر هەنگاوی کۆمەڵایەتی داهاتوو.",
    ],
  },
  {
    en: [
      "One person’s distance isn’t your full lovability.",
      "You can hurt without concluding you’re unwanted by everyone.",
      "You deserve reciprocal care.",
      "You can take space to recover dignity.",
      "Your worth stays while you heal.",
    ],
    ku: [
      "دووری یەک کەس هەموو شایستەیی خۆشەویستیت نییە.",
      "دەتوانیت بئێشیت بەبێ ئەنجامگیری کە هەمووان نایانەوێت.",
      "شایستەی چاودێری هاوسەنگیت.",
      "دەتوانیت بۆشایی وەربگریت بۆ گەڕاندنەوەی کەرامەت.",
      "بەهایت دەمێنێتەوە کاتێک چاک دەبیتەوە.",
    ],
  }
);

const comparison = cat(
  {
    en: [
      "Comparison is stealing your peace right now.",
      "I hear the sting of measuring yourself against others.",
      "“Everyone else” can become a painful story.",
      "You’re feeling behind — that ache is real.",
      "Looking sideways often makes your own path feel smaller.",
      "I hear envy mixed with self-doubt.",
      "You’re naming the pressure of not matching someone else’s timeline.",
      "Comparison can turn ordinary days into failure.",
      "It sounds like someone else’s highlight is hurting you.",
      "You’re tired of feeling less than.",
    ],
    ku: [
      "بەراورد ئێستا ئارامیت دەدزێت.",
      "گوێم لە ئازاری پێوانەکردنی خۆت بەرامبەر کەسانی تر.",
      "«هەموو کەسێکی تر» دەتوانێت ببێتە چیرۆکێکی ئازاربەخش.",
      "هەست دەکەیت لە دواوەیت — ئەم ئازارە ڕاستەقینەیە.",
      "سەیری لایەکی تر زۆرجار ڕێگای خۆت بچووکتر دەکات.",
      "گوێم لە حەسوودی تێکەڵ بە گومانی خۆتە.",
      "فشاری نەگونجان لەگەڵ کاتی کەسێکی تر ناودەبەیت.",
      "بەراورد دەتوانێت ڕۆژی ئاسایی بکاتە شکست.",
      "وەک هایلایتی کەسێکی تر برینداری کردبێت.",
      "ماندوویت لە هەستی کەمتربوون.",
    ],
  },
  {
    en: [
      "Someone else’s chapter is not a fair scorecard for yours.",
      "What you see of others is rarely their full private struggle.",
      "Different timelines don’t mean you are behind as a person.",
      "Comparison shrinks context and exaggerates gaps.",
      "You can want growth without using others as a weapon against yourself.",
      "Your pace can be valid even when it looks quieter.",
      "Highlight reels are incomplete evidence.",
      "Feeling behind often means you care — not that you failed.",
      "You can borrow inspiration without swallowing shame.",
      "Worth isn’t a race finish line.",
      "You are allowed a path that doesn’t match theirs.",
      "Progress can be invisible from the outside.",
      "One person’s advantage doesn’t erase your effort.",
      "You can return attention to your next inch of growth.",
      "Comparison is a habit you can interrupt gently.",
    ],
    ku: [
      "بەشی کەسێکی تر تابلۆی یاری دادپەروەر نییە بۆ بەشەکەی تۆ.",
      "ئەوەی لە کەسانی تر دەبینیت بەدەگمەن هەموو خەباتی تایبەتیانە.",
      "کاتی جیاواز مانای ئەوە نییە وەک کەسێک لە دواوەیت.",
      "بەراورد دەق کەم دەکاتەوە و بۆشایی گەورە دەکات.",
      "دەتوانیت گەشە بخوازیت بەبێ بەکارهێنانی کەسانی تر وەک چەک دژی خۆت.",
      "خێراییت دەتوانێت ڕەوا بێت تەنانەت کاتێک بێدەنگتر دەردەکەوێت.",
      "هایلایت ڕیل بەڵگەی ناتەواوە.",
      "هەستی دواکەوتن زۆرجار واتە گرنگت پێیەتی — نەک شکستت هێناوە.",
      "دەتوانیت ئیلهام وەربگریت بەبێ قووتدانی شەرم.",
      "بەها هێڵی کۆتایی پێشبڕکێ نییە.",
      "مامۆڵەت هەیە ڕێگایەکت هەبێت کە لەگەڵیان ناگونجێت.",
      "پێشکەوتن دەتوانێت لە دەرەوە نادیار بێت.",
      "باشتری یەک کەس هەوڵەکانت ناسڕێتەوە.",
      "دەتوانیت سەرنج بگەڕێنیتەوە بۆ اینچی داهاتووی گەشەت.",
      "بەراورد خووێکە دەتوانیت بە نەرمی ببڕیت.",
    ],
  },
  {
    en: [
      "I can walk my own pace without calling it failure.",
      "Their chapter isn’t my scorecard.",
      "I can want growth without shaming myself.",
      "I return to my next small step.",
      "I am allowed a quieter path.",
      "What I see of others is incomplete.",
      "My effort still counts.",
      "I can interrupt comparison gently.",
      "Worth isn’t a race.",
      "I can feel envy and still stay kind to myself.",
      "My timeline can be different and valid.",
      "I choose my inch of progress today.",
      "I don’t have to match anyone to matter.",
      "Inspiration yes; self-attack no.",
      "I am enough for the next honest step.",
    ],
    ku: [
      "دەتوانم بە خێرایی خۆم بڕۆم بەبێ ناوی شکست.",
      "بەشی ئەوان تابلۆی یاری من نییە.",
      "دەتوانم گەشە بخوازم بەبێ شەرمەزاری خۆم.",
      "دەگەڕێمەوە بۆ هەنگاوی بچووکی داهاتووم.",
      "مامۆڵەم هەیە ڕێگای بێدەنگترم هەبێت.",
      "ئەوەی لە کەسانی تر دەبینم ناتەواوە.",
      "هەوڵەکەم هێشتا دەژمێردرێت.",
      "دەتوانم بەراورد بە نەرمی ببڕم.",
      "بەها پێشبڕکێ نییە.",
      "دەتوانم حەسوودی هەست بکەم و هێشتا میهرەبان بم لەگەڵ خۆم.",
      "کاتەکەم دەتوانێت جیاواز و ڕەوا بێت.",
      "ئەمڕۆ اینچی پێشکەوتنی خۆم هەڵدەبژێرم.",
      "پێویست ناکات لەگەڵ کەس بگونجم بۆ گرنگبوون.",
      "ئیلهام بەڵێ؛ هێرشی سەر خۆم نەخێر.",
      "بۆ هەنگاوی ڕاستگۆی داهاتوو بەسم.",
    ],
  },
  {
    en: [
      "Mute or step away from the comparing feed for an hour.",
      "Write your next personal goal in one line only.",
      "Name one strength you used this week.",
      "Do a task that belongs only to your life.",
      "Bless their win silently, then return to yours.",
      "Limit “everyone else” talk for the evening.",
      "Measure today by effort, not ranking.",
      "Take a walk without your phone.",
      "Ask what you need, not what they have.",
      "Celebrate one inch you moved recently.",
    ],
    ku: [
      "بۆ یەک کاتژمێر فیدەکەی بەراورد بێدەنگ بکە یان لێی دوور بکەوەرەوە.",
      "ئامانجی کەسیی داهاتووت تەنها لە یەک هێڵدا بنووسە.",
      "یەک هێز ناوببە کە ئەم هەفتەیە بەکارت هێنا.",
      "ئەرکێک بکە کە تەنها هی ژیانی خۆتە.",
      "بێدەنگ سەرکەوتنیان پیرۆز بکە، پاشان بگەڕێوە بۆ هی خۆت.",
      "قسەی «هەموو کەسێکی تر» بۆ ئێوارەکە سنووردار بکە.",
      "ئەمڕۆ بە هەوڵ بپێوە، نەک بە ڕیزبەندی.",
      "بێ مۆبایل پیاسەیەک بکە.",
      "بپرسە تۆ چیت پێویستە، نەک ئەوان چیان هەیە.",
      "یەک اینچ پیرۆز بکە کە بەم دواییە جووڵات.",
    ],
  },
  {
    en: [
      "Their chapter isn’t your scorecard.",
      "You can walk your own pace without calling it failure.",
      "Worth isn’t a race.",
      "Return to your next small step.",
      "You don’t have to match anyone to matter.",
    ],
    ku: [
      "بەشی ئەوان تابلۆی یاری تۆ نییە.",
      "دەتوانیت بە خێرایی خۆت بڕۆیت بەبێ ناوی شکست.",
      "بەها پێشبڕکێ نییە.",
      "بگەڕێوە بۆ هەنگاوی بچووکی داهاتووت.",
      "پێویست ناکات لەگەڵ کەس بگونجیت بۆ گرنگبوون.",
    ],
  }
);

const uncertainty = cat(
  {
    en: [
      "Not knowing what to do can feel like being lost.",
      "I hear confusion without a clear map.",
      "Uncertainty is uncomfortable — you’re naming it honestly.",
      "It sounds like options are foggy.",
      "You’re stuck between paths.",
      "I hear the strain of indecision.",
      "Not knowing who you are in this season is heavy.",
      "You’re waiting for clarity that hasn’t arrived.",
      "Doubt about the next step is present.",
      "This unsure place deserves patience.",
    ],
    ku: [
      "نەزانینی چی بکەیت دەتوانێت وەک ونبوون هەست پێ بکرێت.",
      "گوێم لە سەرلێشێواوی بێ نەخشەی ڕوون.",
      "نادڵنیایی نارەحەتە — بە ڕاستگۆیی ناوی دەبەیت.",
      "وەک هەڵبژاردنەکان تەمئاوی بن.",
      "لە نێوان ڕێگاکاندا قەتیسی.",
      "گوێم لە فشاری بڕیارنەدان.",
      "نەزانینی کێیت لەم وەرزەدا قورسە.",
      "چاوەڕێی ڕوونیت کە هێشتا نەهاتووە.",
      "گومان لەسەر هەنگاوی داهاتوو ئامادەیە.",
      "ئەم شوێنە نادڵنیایە شایستەی ئارامگیرییە.",
    ],
  },
  {
    en: [
      "You don’t need perfect certainty to take a tiny next step.",
      "Confusion can be a season, not a permanent identity.",
      "Unsure minds often need smaller questions, not bigger pressure.",
      "It’s okay to know only the next hour.",
      "Clarity often follows action, not the other way around.",
      "Being lost can mean you’re between chapters.",
      "You can choose reversible steps while you learn.",
      "Not knowing everything doesn’t mean you know nothing.",
      "Identity can be under construction without being broken.",
      "Patience with uncertainty is a form of strength.",
      "You can gather one fact instead of forcing a life decision.",
      "Fog lifts unevenly — small orientation still helps.",
      "You are allowed to ask for guidance.",
      "Indecision softens when options are written down.",
      "A provisional choice can be enough for today.",
    ],
    ku: [
      "پێویستت بە دڵنیایی کامڵ نییە بۆ هەنگاوێکی بچووک.",
      "سەرلێشێواوی دەتوانێت وەرز بێت، نەک ناسنامەی هەمیشەیی.",
      "مێشکی نادڵنیا زۆرجار پێویستی بە پرسیاری بچووکتر هەیە، نەک فشاری گەورەتر.",
      "ئاساییە تەنها کاتژمێری داهاتوو بزانیت.",
      "ڕوونی زۆرجار دوای کردار دێت، نەک پێچەوانە.",
      "ونبوون دەتوانێت واتە لە نێوان بەشەکاندا بیت.",
      "دەتوانیت هەنگاوی گەڕاوە هەڵبژێریت کاتێک فێردەبیت.",
      "نەزانینی هەموو شت مانای نەزانینی هیچ نییە.",
      "ناسنامە دەتوانێت لە ژێر دروستکردندا بێت بەبێ تێکچوون.",
      "ئارامگیری لەگەڵ نادڵنیایی جۆرێک لە هێزە.",
      "دەتوانیت یەک ڕاستی کۆبکەیتەوە لەجیاتی بڕیاری ژیانی زۆرەملێ.",
      "تەم ناڕێک هەڵدەکەوێت — ئاراستەکردنێکی بچووک هێشتا یارمەتی دەدات.",
      "مامۆڵەت هەیە ڕێنمایی بخوازیت.",
      "بڕیارنەدان نەرم دەبێتەوە کاتێک هەڵبژاردنەکان دەنووسرێن.",
      "هەڵبژاردەیەکی کاتی بۆ ئەمڕۆ بەسە.",
    ],
  },
  {
    en: [
      "I only need the next small step, not the whole map.",
      "I can choose something reversible for today.",
      "Uncertainty can be temporary.",
      "I am allowed to not know yet.",
      "I can write options instead of spinning.",
      "One fact is enough to start.",
      "I can ask for guidance.",
      "My identity can be under construction.",
      "I don’t have to force a forever decision tonight.",
      "Clarity can follow a tiny action.",
      "I can know the next hour.",
      "Being between chapters is allowed.",
      "I can wait without calling myself lost forever.",
      "A provisional choice is enough.",
      "I can move gently while unsure.",
    ],
    ku: [
      "تەنها پێویستیم بە هەنگاوی بچووکی داهاتووە، نەک هەموو نەخشە.",
      "دەتوانم بۆ ئەمڕۆ شتێکی گەڕاوە هەڵبژێرم.",
      "نادڵنیایی دەتوانێت کاتی بێت.",
      "مامۆڵەم هەیە هێشتا نەزانم.",
      "دەتوانم هەڵبژاردنەکان بنووسم لەجیاتی سووڕانەوە.",
      "یەک ڕاستی بۆ دەستپێک بەسە.",
      "دەتوانم ڕێنمایی بخوازم.",
      "ناسنامەم دەتوانێت لە ژێر دروستکردندا بێت.",
      "پێویست ناکات ئەمشەو بڕیاری هەمیشەیی زۆرەملێ بکەم.",
      "ڕوونی دەتوانێت دوای کردارێکی بچووک بێت.",
      "دەتوانم کاتژمێری داهاتوو بزانم.",
      "لە نێوان بەشەکاندا بوون ڕێگەپێدراوە.",
      "دەتوانم چاوەڕێ بکەم بەبێ ناوی ونبوونی هەمیشەیی.",
      "هەڵبژاردەی کاتی بەسە.",
      "دەتوانم بە نەرمی بجووڵێم کاتێک نادڵنیام.",
    ],
  },
  {
    en: [
      "Write two options and circle the gentler one for today.",
      "Decide only the next hour’s plan.",
      "Ask one trusted person a practical question.",
      "Gather one piece of information, then stop.",
      "Take a walk and notice what feels slightly lighter.",
      "Sleep on big decisions when you can.",
      "Shrink the choice to a reversible trial.",
      "List what you already know in three bullets.",
      "Remove one option that clearly drains you.",
      "Choose orientation over perfection.",
    ],
    ku: [
      "دوو هەڵبژاردە بنووسە و نەرمترینیان بۆ ئەمڕۆ هەڵبژێرە.",
      "تەنها پلانی کاتژمێری داهاتوو بڕیار بدە.",
      "یەک پرسیاری کرداری لە کەسێکی متمانەپێکراو بپرسە.",
      "یەک پارچە زانیاری کۆبکەرەوە، پاشان بوەستە.",
      "پیاسە بکە و سەرنجی بدە چی کەمێک سووکتر هەست دەکات.",
      "کاتێک دەتوانیت، بڕیاری گەورە بۆ دوای خەو بهێڵەرەوە.",
      "هەڵبژاردەکە بچووک بکەرەوە بۆ تاقیکردنەوەیەکی گەڕاوە.",
      "ئەوەی پێشتر دەیزانیت لە سێ خاڵدا بنووسە.",
      "یەک هەڵبژاردە لاببە کە بە ڕوونی ماندووت دەکات.",
      "ئاراستەکردن هەڵبژێرە لەجیاتی کامڵی.",
    ],
  },
  {
    en: [
      "You don’t need the whole map — only the next small step.",
      "Uncertainty can be a season, not your identity.",
      "A provisional choice is enough for today.",
      "You are allowed to not know yet.",
      "Clarity can follow a tiny action.",
    ],
    ku: [
      "پێویستت بە هەموو نەخشە نییە — تەنها هەنگاوی بچووکی داهاتوو.",
      "نادڵنیایی دەتوانێت وەرز بێت، نەک ناسنامەت.",
      "هەڵبژاردەی کاتی بۆ ئەمڕۆ بەسە.",
      "مامۆڵەت هەیە هێشتا نەزانیت.",
      "ڕوونی دەتوانێت دوای کردارێکی بچووک بێت.",
    ],
  }
);

const general = cat(
  {
    en: [
      "I hear someone carrying a heavy thought.",
      "Something in you needs gentleness right now.",
      "You’re naming distress — that honesty matters.",
      "This feels hard, and you’re not imagining that.",
      "I hear pain looking for words.",
      "You’re going through a rough patch.",
      "A heavy feeling is present.",
      "It takes courage to write this down.",
      "You’re allowed to struggle aloud here.",
      "I hear you.",
    ],
    ku: [
      "گوێم لە کەسێکە بیرێکی قورس هەڵدەگرێت.",
      "شتێک لەناوت ئێستا پێویستی بە نەرمی هەیە.",
      "ناڕەحەتی ناودەبەیت — و ئەم ڕاستگۆییە گرنگە.",
      "ئەمە سەخت هەست دەکات، و خەیاڵ ناکەیت.",
      "گوێم لە ئازارێکە وشە دەگەڕێت.",
      "لە قۆناغێکی قورسدا تێدەپەڕیت.",
      "هەستێکی قورس ئامادەیە.",
      "ئازایەتی دەوێت ئەمە بنووسیت.",
      "مامۆڵەت هەیە لێرە بە دەنگ خەبات بکەیت.",
      "گوێم لێتە.",
    ],
  },
  {
    en: [
      "A hard feeling can be true without being the whole truth about you.",
      "You can hold distress and still take one kind next step.",
      "Painful thoughts visit; they don’t have to move in forever.",
      "You deserve care while things feel heavy.",
      "Naming the hurt is already a form of steadiness.",
      "You don’t have to fix everything tonight.",
      "Gentle support can coexist with difficult emotions.",
      "This moment can be heavy without defining your whole week.",
      "You are allowed to go slowly.",
      "Feeling bad doesn’t make you bad.",
      "You can seek comfort without waiting to feel strong.",
      "Small kindness counts when big solutions aren’t ready.",
      "Your experience matters even if it’s messy.",
      "You can breathe first, decide later.",
      "Being human includes hard hours.",
    ],
    ku: [
      "هەستێکی قورس دەتوانێت ڕاست بێت بەبێ بوون بە هەموو ڕاستی دەربارەی تۆ.",
      "دەتوانیت ناڕەحەتی هەڵبگریت و هێشتا هەنگاوێکی میهرەبان هەڵبگریت.",
      "بیری ئازاربەخش سەردان دەکات؛ پێویست ناکات بۆ هەمیشە نیشتەجێ ببێت.",
      "شایستەی چاودێریت کاتێک شتەکان قورسن.",
      "ناونانی ئازار پێشتر جۆرێک لە جێگیرییە.",
      "پێویست ناکات ئەمشەو هەموو شت چارەسەر بکەیت.",
      "پشتگیری نەرم دەتوانێت لەگەڵ هەستی قورس پێکەوە بێت.",
      "ئەم کاتە دەتوانێت قورس بێت بەبێ دیاریکردنی هەموو هەفتەکەت.",
      "مامۆڵەت هەیە هێواش بڕۆیت.",
      "هەستی خراپ تۆ ناکاتە کەسی خراپ.",
      "دەتوانیت ئارامی بخوازیت بەبێ چاوەڕێی هەستی بەهێزی.",
      "میهرەبانی بچووک دەژمێردرێت کاتێک چارەسەری گەورە ئامادە نییە.",
      "ئەزموونت گرنگە تەنانەت ئەگەر تێکەڵ بێت.",
      "دەتوانیت یەکەم هەناسە بدەیت، دواتر بڕیار بدەیت.",
      "مرۆڤ بوون کاتژمێری قورسیش تێدایە.",
    ],
  },
  {
    en: [
      "I can go gently with myself right now.",
      "This feeling is visiting — I can meet it with care.",
      "I don’t have to fix everything tonight.",
      "One kind next step is enough.",
      "I am allowed to struggle and still deserve softness.",
      "I can breathe first.",
      "Hard hours happen; I can survive this one.",
      "I matter even when I feel messy.",
      "I can ask for comfort.",
      "Small kindness counts.",
      "I can hold this without attacking myself.",
      "I am human, and this is a human moment.",
      "I can rest inside the difficulty.",
      "Gentleness is allowed.",
      "I can take the next minute only.",
    ],
    ku: [
      "دەتوانم ئێستا بە نەرمی لەگەڵ خۆم بڕۆم.",
      "ئەم هەستە سەردان دەکات — دەتوانم بە چاودێری پێشوازی لێ بکەم.",
      "پێویست ناکات ئەمشەو هەموو شت چارەسەر بکەم.",
      "یەک هەنگاوی میهرەبان بەسە.",
      "مامۆڵەم هەیە خەبات بکەم و هێشتا شایستەی نەرمی بم.",
      "دەتوانم یەکەم هەناسە بدەم.",
      "کاتژمێری قورس ڕوودەدات؛ دەتوانم ئەمە بەرگە بگرم.",
      "گرنگم تەنانەت کاتێک تێکەڵ هەست دەکەم.",
      "دەتوانم داوای ئارامی بکەم.",
      "میهرەبانی بچووک دەژمێردرێت.",
      "دەتوانم ئەمە هەڵبگرم بەبێ هێرشکردنە سەر خۆم.",
      "مرۆڤم، و ئەمە کاتێکی مرۆڤایەتییە.",
      "دەتوانم لەناو سەختیدا پشوو بدەم.",
      "نەرمی ڕێگەپێدراوە.",
      "دەتوانم تەنها خولەکی داهاتوو هەڵبگرم.",
    ],
  },
  {
    en: [
      "Breathe slowly twice, then choose one tiny comfort.",
      "Drink water and sit still for one minute.",
      "Write the feeling in one line and stop.",
      "Put a hand on your chest and soften your shoulders.",
      "Step outside or open a window briefly.",
      "Play a calm sound for a few minutes.",
      "Message someone safe if you want company.",
      "Do one ordinary care act: wash face or tidy a cup.",
      "Reduce tonight’s demands by one item.",
      "Rest your eyes from screens for five minutes.",
    ],
    ku: [
      "دوو جار هێواش هەناسە بدە، پاشان یەک ئارامیی بچووک هەڵبژێرە.",
      "ئاو بخۆرەوە و یەک خولەک دانیشە.",
      "هەستەکە لە یەک هێڵدا بنووسە و بوەستە.",
      "دەستت لەسەر سنگت دابنێ و شانەکانت نەرم بکە.",
      "کەمێک بچۆ دەرەوە یان پەنجەرە بکەرەوە.",
      "چەند خولەک دەنگێکی ئارام لێبدە.",
      "ئەگەر هاوڕێیەتی دەتەوێت بۆ کەسێکی سەلامەت بنووسە.",
      "یەک کرداری چاودێری ئاسایی: شوشتنی ڕووخسار یان ڕێکخستنی گڵاسێک.",
      "داواکارییەکانی ئەمشەو بە یەک شت کەم بکەرەوە.",
      "پێنج خولەک چاوت لە شاشە پشوو بدە.",
    ],
  },
  {
    en: [
      "You can go gently with yourself right now.",
      "This feeling can be true without being the whole of you.",
      "One kind next step is enough.",
      "You don’t have to fix everything tonight.",
      "Gentleness is allowed.",
    ],
    ku: [
      "دەتوانیت ئێستا بە نەرمی لەگەڵ خۆت بڕۆیت.",
      "ئەم هەستە دەتوانێت ڕاست بێت بەبێ بوون بە هەموو تۆ.",
      "یەک هەنگاوی میهرەبان بەسە.",
      "پێویست ناکات ئەمشەو هەموو شت چارەسەر بکەیت.",
      "نەرمی ڕێگەپێدراوە.",
    ],
  }
);

export const BANKS = {
  self_worth,
  failure,
  loneliness,
  appearance,
  exhaustion,
  anxiety,
  guilt,
  anger,
  hopelessness,
  overthinking,
  rejection,
  comparison,
  uncertainty,
  general,
};
