/**
 * Kurdana Thought Mirror — local category keywords (EN + Sorani).
 * Not AI. Runs entirely on-device.
 */

export const CATEGORIES = [
  "self_worth",
  "failure",
  "loneliness",
  "appearance",
  "exhaustion",
  "anxiety",
  "guilt",
  "anger",
  "hopelessness",
  "overthinking",
  "rejection",
  "comparison",
  "uncertainty",
  "general",
];

/** @type {Record<string, { en: string[], ku: string[] }>} */
export const KEYWORDS = {
  self_worth: {
    en: [
      "dumb",
      "stupid",
      "useless",
      "worthless",
      "not good enough",
      "hate myself",
      "i'm nothing",
      "im nothing",
      "no value",
      "idiot",
      "pathetic",
      "inadequate",
      "not enough",
      "broken",
      "failure of a person",
    ],
    ku: [
      "بێسوود",
      "هیچ سوود",
      "بێبەها",
      "لە خۆم ڕقم",
      "ڕقم لە خۆم",
      "بێنرخ",
      "کەمە",
      "باش نیم",
      "هیچ نیم",
      "ناتەواو",
      "بێبەهایی",
      "گەمژە",
      "گێل",
    ],
  },
  failure: {
    en: [
      "failed",
      "failure",
      "ruined",
      "messed up",
      "can't do anything right",
      "cant do anything right",
      "always lose",
      "always fail",
      "i failed",
      "screw up",
      "i ruin",
      "never succeed",
      "keep failing",
    ],
    ku: [
      "شکست",
      "شکەست",
      "هەمیشە دەشکێم",
      "هەمیشە شکەست",
      "تێکمدا",
      "هیچ ناکەم ڕاست",
      "دەدۆڕێم",
      "سەرکەوتوو نابم",
      "خراپم کرد",
    ],
  },
  loneliness: {
    en: [
      "alone",
      "lonely",
      "nobody cares",
      "no one cares",
      "no one loves",
      "nobody loves",
      "unwanted",
      "isolated",
      "by myself",
      "no friends",
      "left out",
    ],
    ku: [
      "تەنها",
      "تەنیایی",
      "کەس گرنگی",
      "کەس خۆشی ناوێت",
      "کەس خۆشی نایەوێت",
      "بێ کەس",
      "دەرکراو",
      "جیاکراوە",
    ],
  },
  appearance: {
    en: [
      "ugly",
      "fat",
      "hate my body",
      "not beautiful",
      "look terrible",
      "hideous",
      "disgusting looking",
      "hate how i look",
      "not pretty",
      "my body",
    ],
    ku: [
      "ناشرین",
      "قەڵەو",
      "ڕقم لە جەستەم",
      "جوان نیم",
      "ناشرین دەردەکەوم",
      "لە خۆم ڕازیم نییە",
      "شێوەم",
      "جەستەم",
    ],
  },
  exhaustion: {
    en: [
      "tired",
      "exhausted",
      "drained",
      "no energy",
      "burned out",
      "burnt out",
      "worn out",
      "can't keep going",
      "so tired",
      "fatigued",
    ],
    ku: [
      "ماندوو",
      "سووتاوم",
      "هێزم نەما",
      "بێ وزە",
      "زۆر ماندووم",
      "نەماوم",
      "بێ توانا",
    ],
  },
  anxiety: {
    en: [
      "scared",
      "afraid",
      "worried",
      "panic",
      "something bad",
      "can't calm down",
      "cant calm down",
      "anxious",
      "nervous",
      "terrified",
      "on edge",
      "what if",
    ],
    ku: [
      "دڵەڕاوکێ",
      "ترس",
      "دەترسم",
      "نیگەران",
      "ناتوانم ئارام ببمەوە",
      "شتێکی خراپ",
      "پەنیک",
      "هەڵچووم",
    ],
  },
  guilt: {
    en: [
      "guilty",
      "guilt",
      "shame",
      "ashamed",
      "my fault",
      "should have",
      "shouldn't have",
      "i ruined it",
      "blame myself",
    ],
    ku: [
      "گوناه",
      "شەرم",
      "هەڵەم",
      "تاوانم",
      "دەبوو",
      "نەدەبوو",
      "خۆم سەرزنشت",
    ],
  },
  anger: {
    en: [
      "angry",
      "furious",
      "hate them",
      "so mad",
      "rage",
      "pissed",
      "fed up",
      "can't stand",
      "cant stand",
    ],
    ku: [
      "تووڕە",
      "قین",
      "ڕقم لێیان",
      "بێزار",
      "ناتوانم بەرگەی",
      "هەڵچووم",
    ],
  },
  hopelessness: {
    en: [
      "hopeless",
      "no point",
      "what's the point",
      "nothing will change",
      "give up",
      "giving up",
      "no future",
      "never get better",
      "pointless",
    ],
    ku: [
      "بێ هیوا",
      "هیچ مانایەکی نییە",
      "گۆڕانکاری نابێت",
      "دەستبەردار",
      "هیچ داهاتوویەک",
      "باشتر نابێت",
    ],
  },
  overthinking: {
    en: [
      "can't stop thinking",
      "cant stop thinking",
      "thinking too much",
      "mind won't stop",
      "stuck in my head",
      "overthinking",
      "racing thoughts",
      "spiraling",
      "ruminate",
    ],
    ku: [
      "زۆر بیر دەکەمەوە",
      "ناتوانم بیرکردنەوە ڕابگرم",
      "مێشکم ڕاناوەستێت",
      "لە سەرم قەتیسم",
      "بیرکردنەوەی زۆر",
      "خەریکە زۆر بیر",
    ],
  },
  rejection: {
    en: [
      "rejected",
      "ignored me",
      "left me",
      "ghosted",
      "don't want me",
      "dont want me",
      "turned away",
      "pushed away",
      "abandoned",
    ],
    ku: [
      "ڕەتکرایەوە",
      "پشتگوێی خستم",
      "جێهێشتم",
      "نایانەوێت",
      "دوور خرایەوە",
      "بەجێهێڵراو",
    ],
  },
  comparison: {
    en: [
      "everyone else",
      "better than me",
      "not like them",
      "compare",
      "behind everyone",
      "less than",
      "they have",
      "why can't i",
      "why cant i",
    ],
    ku: [
      "هەموو کەسێکی تر",
      "باشترن لە من",
      "بەراورد",
      "لە دوای هەمووانم",
      "کەمتر",
      "بۆچی من ناتوانم",
    ],
  },
  uncertainty: {
    en: [
      "don't know what to do",
      "dont know what to do",
      "confused",
      "lost",
      "unsure",
      "no idea",
      "stuck",
      "don't know who i am",
      "uncertain",
    ],
    ku: [
      "نامزانم چی بکەم",
      "سەرلێشێواو",
      "ونبووم",
      "دڵنیا نیم",
      "قەتیسم",
      "نامزانم کێم",
    ],
  },
  general: {
    en: ["sad", "hurt", "pain", "heavy", "bad day", "struggling", "hard"],
    ku: ["خەمگین", "بریندار", "ئازار", "قورس", "ڕۆژی خراپ", "سەخت"],
  },
};

export const INTENSITY_MARKERS = {
  en: [
    "always",
    "never",
    "completely",
    "totally",
    "hate",
    "can't stand",
    "cant stand",
    "everything",
    "nothing",
    "forever",
    "so much",
    "really",
    "extremely",
  ],
  ku: ["هەمیشە", "هەرگیز", "تەواو", "زۆر", "ڕقم", "هیچ", "هەموو شت", "بۆ هەمیشە"],
};
